{
  "hash": "84910547052e21a153db20c35e49026f",
  "result": {
    "engine": "knitr",
    "markdown": "# Probabilistic Interpolation: Regression Kriging\n\n\n::: {.cell}\n\n:::\n\n\n## Big Idea\nPlain kriging uses the spatial structure of the response variable itself to make predictions. That works well, but it ignores something we often have access to: variables that are cheap to measure everywhere and that correlate with the thing we care about. Distance to a river, elevation, soil type, and land cover can all be derived from GIS or remote sensing data across an entire study area, even when your expensive response variable is only measured at a handful of sample points. Regression kriging (RK) combines a regression model using those covariates with kriging of the regression residuals, giving you better predictions than either approach alone.\n\n## Reading\n@meng2013 provide a (mostly) readable description of regression kriging and compare it to the kind of interpolation approaches we've looked at already. Give it a heavy skim.\n\n## Packages\nThe `gstat`[@R-gstat] package is your friend. But we will need some of our recent collaborators as well including `terra`[@R-terra] and `tidyterra`[@R-tidyterra], plus `sf`[@R-sf] and `tidyverse`[@R-tidyverse] for the usual data wrangling. We'll use `cowplot`[@R-cowplot] to arrange plots at the end.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(sf)\nlibrary(terra)\nlibrary(tidyterra)\nlibrary(gstat)\nlibrary(cowplot)\n```\n:::\n\n\n## Overview of RK\nThe basic idea is a two-step process. First, fit an OLS regression of your response variable on whatever covariates you have available at both your sample locations and your prediction grid. Second, take the residuals from that regression, fit a variogram to them, and krige those residuals across the prediction grid. The final RK prediction at any location is the OLS fitted value plus the kriged residual:\n\n$$\\hat{Z}_{RK}(s_0) = \\hat{Z}_{OLS}(s_0) + \\hat{\\varepsilon}(s_0)$$\n\nThe OLS surface captures the broad, covariate-driven trend: organic matter is higher near the river, lower on certain soil types, and so on. In geostatistics, this large-scale spatially varying mean is called the trend, not a trend over time but a systematic variation across space driven by covariates. The kriged residual surface captures the local spatial deviations from that trend, the pockets where organic matter is a bit higher or lower than the covariates alone would predict, based on what we observe at nearby sample points. Adding them together gives a prediction that is informed by both the large-scale drivers and the local spatial structure.\n\nThe residuals from the OLS model represent the spatial variation that the covariates couldn't explain. If those residuals are spatially autocorrelated (and they often are), kriging can extract useful information from their spatial structure. In a standard OLS setting, autocorrelated residuals are a problem because they violate the independence assumption. In RK, they're an opportunity.\n\nRK is used more and more commonly now that cheap and powerful covariates can be derived from remote sensing and GIS data. Elevation grids, land cover maps, distance-to-feature layers: if it predicts your response and you have it everywhere, it can go in the model.\n\n::: {.callout-note}\nIf you want a refresher on how to fit an OLS model and then apply it to new data with `predict`, see the [Predicting New Data aside](09xAsidePredictingNewData.html). That pattern is the foundation of the RK workflow.\n:::\n\n## Back to the Netherlands\n\nLet's look at a real-world example of RK using, you guessed it, the Meuse River data. I'm pretty sick of these data but they are familiar to us. We've used `meuse.all` quite a bit and we've used `meuse.grid` as an empty grid to interpolate into. But `meuse.grid` has other variables in it that we haven't used yet, and some of those overlap with `meuse.all`. That overlap is what makes RK possible here.\n\n### The Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(meuse.all)\nstr(meuse.all)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t164 obs. of  17 variables:\n $ sample     : num  1 2 3 4 5 6 7 8 9 10 ...\n $ x          : num  181072 181025 181165 181298 181307 ...\n $ y          : num  333611 333558 333537 333484 333330 ...\n $ cadmium    : num  11.7 8.6 6.5 2.6 2.8 3 3.2 2.8 2.4 1.6 ...\n $ copper     : num  85 81 68 81 48 61 31 29 37 24 ...\n $ lead       : num  299 277 199 116 117 137 132 150 133 80 ...\n $ zinc       : num  1022 1141 640 257 269 ...\n $ elev       : num  7.91 6.98 7.8 7.66 7.48 ...\n $ dist.m     : num  50 30 150 270 380 470 240 120 240 420 ...\n $ om         : num  13.6 14 13 8 8.7 7.8 9.2 9.5 10.6 6.3 ...\n $ ffreq      : num  1 1 1 1 1 1 1 1 1 1 ...\n $ soil       : num  1 1 1 2 2 2 2 1 1 2 ...\n $ lime       : num  1 1 1 0 0 0 0 0 0 0 ...\n $ landuse    : Factor w/ 16 levels \"Aa\",\"Ab\",\"Ag\",..: 4 4 4 11 4 11 4 2 2 16 ...\n $ in.pit     : logi  FALSE FALSE FALSE FALSE FALSE FALSE ...\n $ in.meuse155: logi  TRUE TRUE TRUE TRUE TRUE TRUE ...\n $ in.BMcD    : logi  FALSE FALSE FALSE FALSE FALSE FALSE ...\n```\n\n\n:::\n:::\n\nWe know all too well by now that `meuse.all` is a `data.frame` with 164 point measurements of 17 variables. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmeuse.grid <- readRDS(\"data/meuse.grid.Rds\")\nstr(meuse.grid)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t3103 obs. of  7 variables:\n $ x     : num  181180 181140 181180 181220 181100 ...\n $ y     : num  333740 333700 333700 333700 333660 ...\n $ part.a: num  1 1 1 1 1 1 1 1 1 1 ...\n $ part.b: num  0 0 0 0 0 0 0 0 0 0 ...\n $ dist  : num  0 0 0.0122 0.0435 0 ...\n $ soil  : Factor w/ 3 levels \"1\",\"2\",\"3\": 1 1 1 1 1 1 1 1 1 1 ...\n $ ffreq : Factor w/ 3 levels \"1\",\"2\",\"3\": 1 1 1 1 1 1 1 1 1 1 ...\n```\n\n\n:::\n:::\n\n\nAnd `meuse.grid` is a `data.frame` with 3103 points on a grid and 7 variables. \n\nThree variables are shared between `meuse.all` and `meuse.grid`: distance to the river (normalized 0 to 1), soil type (three classes), and flooding frequency class (also three classes). Because we have these at every grid cell, we can build a regression model using them as predictors and then apply that model across the whole study area. See `?meuse.all` for details on the variables.\n\nWe'll skip cadmium, zinc, and lead this time and model `om`, percent organic matter in the soil, as a function of `dist` and `soil`. We'll first do this naively with OLS alone, and then add the kriging step to get RK.\n\n\n### Make data as `sf` and clean it up\nFirst we will make both data sets into `sf` objects.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmeusePoints_sf <- st_as_sf(meuse.all, coords = c(\"x\",\"y\"), crs=28992)\nmeuseGrid_sf <- st_as_sf(meuse.grid, coords = c(\"x\",\"y\"), crs=28992)\nmeusePoints_sf\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 164 features and 15 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 178605 ymin: 329714 xmax: 181390 ymax: 333611\nProjected CRS: Amersfoort / RD New\nFirst 10 features:\n   sample cadmium copper lead zinc  elev dist.m   om ffreq soil lime landuse\n1       1    11.7     85  299 1022 7.909     50 13.6     1    1    1      Ah\n2       2     8.6     81  277 1141 6.983     30 14.0     1    1    1      Ah\n3       3     6.5     68  199  640 7.800    150 13.0     1    1    1      Ah\n4       4     2.6     81  116  257 7.655    270  8.0     1    2    0      Ga\n5       5     2.8     48  117  269 7.480    380  8.7     1    2    0      Ah\n6       6     3.0     61  137  281 7.791    470  7.8     1    2    0      Ga\n7       7     3.2     31  132  346 8.217    240  9.2     1    2    0      Ah\n8       8     2.8     29  150  406 8.490    120  9.5     1    1    0      Ab\n9       9     2.4     37  133  347 8.668    240 10.6     1    1    0      Ab\n10     10     1.6     24   80  183 9.049    420  6.3     1    2    0       W\n   in.pit in.meuse155 in.BMcD              geometry\n1   FALSE        TRUE   FALSE POINT (181072 333611)\n2   FALSE        TRUE   FALSE POINT (181025 333558)\n3   FALSE        TRUE   FALSE POINT (181165 333537)\n4   FALSE        TRUE   FALSE POINT (181298 333484)\n5   FALSE        TRUE   FALSE POINT (181307 333330)\n6   FALSE        TRUE   FALSE POINT (181390 333260)\n7   FALSE        TRUE   FALSE POINT (181165 333370)\n8   FALSE        TRUE   FALSE POINT (181027 333363)\n9   FALSE        TRUE   FALSE POINT (181060 333231)\n10  FALSE        TRUE   FALSE POINT (181232 333168)\n```\n\n\n:::\n\n```{.r .cell-code}\nmeuseGrid_sf\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 3103 features and 5 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 178460 ymin: 329620 xmax: 181540 ymax: 333740\nProjected CRS: Amersfoort / RD New\nFirst 10 features:\n   part.a part.b       dist soil ffreq              geometry\n1       1      0 0.00000000    1     1 POINT (181180 333740)\n2       1      0 0.00000000    1     1 POINT (181140 333700)\n3       1      0 0.01222430    1     1 POINT (181180 333700)\n4       1      0 0.04346780    1     1 POINT (181220 333700)\n5       1      0 0.00000000    1     1 POINT (181100 333660)\n6       1      0 0.01222430    1     1 POINT (181140 333660)\n7       1      0 0.03733950    1     1 POINT (181180 333660)\n8       1      0 0.05936620    1     1 POINT (181220 333660)\n9       1      0 0.00135803    1     1 POINT (181060 333620)\n10      1      0 0.01222430    1     1 POINT (181100 333620)\n```\n\n\n:::\n:::\n\n\nOne thing to note here is that the `dist.m` column in `meusePoints_sf` is the distance to the river in meters while `meuseGrid_sf` has distance in relative units (scaled 0 to 1). To make life easier we will add the relative distances to the point data using the `dist` values from `meuseGrid_sf`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# get the relative distance from meuseGrid_sf and add it to meusePoints_sf\nmeuseGrid_dist_sf <- meuseGrid_sf %>% select(dist)\n# join the two objects by the nearest point\nmeusePoints_sf <- st_join(meusePoints_sf, meuseGrid_dist_sf, join = st_nearest_feature)\n# note that we now have relative dist for each point now in the column `dist`\nmeusePoints_sf\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 164 features and 16 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 178605 ymin: 329714 xmax: 181390 ymax: 333611\nProjected CRS: Amersfoort / RD New\nFirst 10 features:\n   sample cadmium copper lead zinc  elev dist.m   om ffreq soil lime landuse\n1       1    11.7     85  299 1022 7.909     50 13.6     1    1    1      Ah\n2       2     8.6     81  277 1141 6.983     30 14.0     1    1    1      Ah\n3       3     6.5     68  199  640 7.800    150 13.0     1    1    1      Ah\n4       4     2.6     81  116  257 7.655    270  8.0     1    2    0      Ga\n5       5     2.8     48  117  269 7.480    380  8.7     1    2    0      Ah\n6       6     3.0     61  137  281 7.791    470  7.8     1    2    0      Ga\n7       7     3.2     31  132  346 8.217    240  9.2     1    2    0      Ah\n8       8     2.8     29  150  406 8.490    120  9.5     1    1    0      Ab\n9       9     2.4     37  133  347 8.668    240 10.6     1    1    0      Ab\n10     10     1.6     24   80  183 9.049    420  6.3     1    2    0       W\n   in.pit in.meuse155 in.BMcD       dist              geometry\n1   FALSE        TRUE   FALSE 0.00135803 POINT (181072 333611)\n2   FALSE        TRUE   FALSE 0.01222430 POINT (181025 333558)\n3   FALSE        TRUE   FALSE 0.10302900 POINT (181165 333537)\n4   FALSE        TRUE   FALSE 0.19009400 POINT (181298 333484)\n5   FALSE        TRUE   FALSE 0.27709000 POINT (181307 333330)\n6   FALSE        TRUE   FALSE 0.36406700 POINT (181390 333260)\n7   FALSE        TRUE   FALSE 0.19009400 POINT (181165 333370)\n8   FALSE        TRUE   FALSE 0.09215160 POINT (181027 333363)\n9   FALSE        TRUE   FALSE 0.18461400 POINT (181060 333231)\n10  FALSE        TRUE   FALSE 0.30970200 POINT (181232 333168)\n```\n\n\n:::\n:::\n\n\nWe will go a step further and use the square root of the distance to the river as a predictor. This gives us a little more leverage on very short distances by stretching out that end of the scale.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmeusePoints_sf <- meusePoints_sf %>% mutate(sqrt_dist = sqrt(dist))\nmeuseGrid_sf <- meuseGrid_sf %>% mutate(sqrt_dist = sqrt(dist))\n```\n:::\n\n\nThe column `om` in `meusePoints_sf` has two missing values. I'm going to drop those rows to keep things clean. Note the new row count after you run this.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmeusePoints_sf <- meusePoints_sf %>% drop_na(om)\n```\n:::\n\n\nAnd we need soil type as a `factor` since it's categorical.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmeusePoints_sf <- meusePoints_sf %>% mutate(soil = factor(soil))\nmeuseGrid_sf <- meuseGrid_sf %>% mutate(soil = factor(soil))\n```\n:::\n\n\n### OLS\nWe'll start with a simple OLS model of organic matter ($y$) as a function of the square root of distance to the river ($x_1$) and soil type ($x_2$): $y=\\beta_0 + \\beta_1x_1+\\beta_2x_2$, with parameters estimated by OLS.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nom_lm <- lm(om~sqrt_dist+soil, data=meusePoints_sf)\nsummary(om_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = om ~ sqrt_dist + soil, data = meusePoints_sf)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-6.8478 -1.4629 -0.1575  1.4344  7.3786 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  11.6894     0.4418  26.460  < 2e-16 ***\nsqrt_dist    -8.9179     1.0902  -8.180 8.79e-14 ***\nsoil2        -1.7178     0.5047  -3.403 0.000843 ***\nsoil3         0.7120     0.8628   0.825 0.410449    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2.473 on 158 degrees of freedom\nMultiple R-squared:  0.4926,\tAdjusted R-squared:  0.4829 \nF-statistic: 51.12 on 3 and 158 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nanova(om_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: om\n           Df Sum Sq Mean Sq F value    Pr(>F)    \nsqrt_dist   1 833.08  833.08 136.197 < 2.2e-16 ***\nsoil        2 105.07   52.54   8.589 0.0002877 ***\nResiduals 158 966.45    6.12                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nBoth distance and soil type are useful predictors of organic matter. Now, after you learn about the pitfalls of using OLS with spatial data you'll be appalled that I'm running this model without checking for autocorrelation in the residuals. But suppress your horror for now, because all we want to do here is show what a purely regression-based prediction surface looks like before we improve on it. Note the below we do the prediction and then make a raster of the output using the function `sf_2_rast` from the prior weeks.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmeuseGrid_sf$omHat <- predict(om_lm, newdata=meuseGrid_sf)\n\nsf_2_rast <- function(sfObject, variable2get = 1){\n  tmp <- sfObject[,variable2get] %>% st_drop_geometry()\n  dfObject <- data.frame(st_coordinates(sfObject), z=tmp)\n  rastObject <- rast(dfObject, crs=crs(sfObject))\n  return(rastObject)\n}\n\nmeuseGrid_rast <- sf_2_rast(meuseGrid_sf, variable2get = \"omHat\")\nggplot() + geom_spatraster(data = meuseGrid_rast,\n                           mapping = aes(fill=omHat)) +\n  scale_fill_terrain_c() +\n  labs(fill = \"omHat\")\n```\n\n::: {.cell-output-display}\n![](09GeostatsRegressionKriging_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\nThe prediction is reasonable, but the residuals are spatially autocorrelated: Moran's I on a four-neighbor object is 0.23, significantly greater than zero. That matters, and we'll come back to it in the GLS module. \n\n### RK Application\nThe OLS model used distance and soil type but ignored everything we know about the spatial structure of organic matter. We threw out the variogram. And we know from the Moran's I above that the residuals are not spatially independent, meaning there is structure left over that the covariates didn't capture. That leftover structure is exactly what kriging is designed to exploit.\n\nLet's look at the variogram of `om` before conditioning on anything\n\n\n::: {.cell}\n\n```{.r .cell-code}\nomVar <- variogram(om~1, meusePoints_sf)\nplot(omVar, pch=20, cex=1.5, col=\"black\",\n     ylab=expression(\"Semivariance (\"*gamma*\")\"),\n     xlab=\"Distance (m)\", main = \"% Soil Organic Matter\")\n```\n\n::: {.cell-output-display}\n![](09GeostatsRegressionKriging_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\nNow we set up a `gstat` object that includes the regression formula. When we call `variogram` on this object, we get the variogram of the OLS residuals, not of `om` itself. The residuals here are just the familiar $e_i = om_i - \\hat{om}_i$ at each sample point: how much higher or lower is the observed organic matter than what distance and soil type alone would predict? We're asking whether those leftover deviations have spatial structure, or whether they're just noise. Compare the two variogram plots and you'll notice the residual variogram has less total variance, which is the variance the covariates explained away. What remains still has spatial structure, which means kriging has something to work with.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nomGstat <- gstat(id = \"omModel\", formula = om ~ sqrt_dist + soil, \n                 data = meusePoints_sf)\nomGstat_obsVariogram <- variogram(omGstat)\nplot(omGstat_obsVariogram, pch=20, cex=1.5, col=\"black\",\n     ylab=expression(\"Semivariance (\"*gamma*\")\"),\n     xlab=\"Distance (m)\", main = \"Model Residuals\")\n```\n\n::: {.cell-output-display}\n![](09GeostatsRegressionKriging_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\nThe residual variogram isn't dramatic, but the semivariance rises from a nugget of around four to a sill of around six. There is spatial structure in the residuals that we can use.\n\nWe fit a theoretical model to it. I'll use a Gaussian model here, though an exponential would also be defensible.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nomGau_variogramModel <- vgm(psill = 2, model = \"Gau\", range = 500, nugget = 4)\nomGau_fittedVariogram <- fit.variogram(object = omGstat_obsVariogram, \n                                       model = omGau_variogramModel)\nplot(omGstat_obsVariogram, omGau_fittedVariogram, pch=20, cex=1.5, col=\"black\",\n     ylab=expression(\"Semivariance (\"*gamma*\")\"),\n     xlab=\"Distance (m)\", main = \"Model Residuals\")\n```\n\n::: {.cell-output-display}\n![](09GeostatsRegressionKriging_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\nNow we update the `gstat` object with the fitted variogram model and predict across the grid. Under the hood, `predict` is doing three things at every grid cell. First, it evaluates the OLS model by plugging `sqrt_dist` and `soil` into $\\hat{\\beta}_0 + \\hat{\\beta}_1 x_1 + \\hat{\\beta}_2 x_2$ to get the covariate-driven trend at that location. Second, it kriging the residuals: it looks at the OLS residuals at the nearby sample points ($e_i = om_i - \\hat{om}_i$) and uses the fitted variogram to estimate what the residual would be at the prediction location. Third, it adds the two together. The first part handles the large-scale pattern that distance and soil type explain. The second part handles the local spatial deviations that the covariates missed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Update the gstat object with the variogram:\nomGstat_w_variogram <- gstat(omGstat, id=\"omModel\", model=omGau_fittedVariogram)\n# And predict\nomHat_sf <- predict(omGstat_w_variogram, newdata = meuseGrid_sf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[using universal kriging]\n```\n\n\n:::\n\n```{.r .cell-code}\nomHat_sf\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 3103 features and 2 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 178460 ymin: 329620 xmax: 181540 ymax: 333740\nProjected CRS: Amersfoort / RD New\nFirst 10 features:\n   omModel.pred omModel.var              geometry\n1      14.33925    5.370484 POINT (181180 333740)\n2      14.38783    5.207101 POINT (181140 333700)\n3      13.21201    5.157301 POINT (181180 333700)\n4      12.16400    5.172975 POINT (181220 333700)\n5      14.40785    5.072086 POINT (181100 333660)\n6      13.24575    5.008217 POINT (181140 333660)\n7      12.37959    5.012552 POINT (181180 333660)\n8      11.85536    5.056317 POINT (181220 333660)\n9      13.99687    4.937392 POINT (181060 333620)\n10     13.24906    4.889664 POINT (181100 333620)\n```\n\n\n:::\n:::\n\n\nTo make this concrete, let's look at all three surfaces: the OLS trend, the kriged residuals, and the final RK prediction that combines them. We have `omHat` from the OLS step already. We can recover the kriged residual surface by subtracting it from the RK prediction.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nomHat_rast <- sf_2_rast(omHat_sf, variable2get = \"omModel.pred\")\n\n# kriged residual surface = RK prediction minus OLS trend\nomHat_sf$krigedResid <- omHat_sf$omModel.pred - meuseGrid_sf$omHat\nomResid_rast <- sf_2_rast(omHat_sf, variable2get = \"krigedResid\")\n\np_ols <- ggplot() +\n  geom_spatraster(data = meuseGrid_rast, mapping = aes(fill=omHat)) +\n  scale_fill_terrain_c(limits=c(0,18)) +\n  labs(title=\"OLS trend\", fill=\"om (%)\") +\n  theme(axis.text=element_blank(), axis.ticks=element_blank())\n\np_resid <- ggplot() +\n  geom_spatraster(data = omResid_rast, mapping = aes(fill=krigedResid)) +\n  scale_fill_gradient2(low=\"blue\", mid=\"white\", high=\"red\", \n                     midpoint=0, na.value=\"transparent\") +\n  labs(title=\"Kriged residuals\", fill=\"resid\") +\n  theme(axis.text=element_blank(), axis.ticks=element_blank())\n\np_rk <- ggplot() +\n  geom_spatraster(data = omHat_rast, mapping = aes(fill=omModel.pred)) +\n  scale_fill_terrain_c(limits=c(0,18)) +\n  labs(fill=\"om (%)\") +\n  theme(axis.text=element_blank(), axis.ticks=element_blank())\n\n\neq <- ggdraw() + draw_label(\"OLS trend  +  Kriged residuals  =  RK prediction\", \n                             fontface=\"italic\", size=11)\n\ntop_row <- plot_grid(p_ols, p_resid, ncol=2)\nplot_grid(top_row, eq, p_rk, nrow=3, rel_heights=c(1, 0.1, 1))\n```\n\n::: {.cell-output-display}\n![](09GeostatsRegressionKriging_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\nThe OLS surface is smooth: it varies only with distance and soil type. The kriged residual surface shows local corrections, positive where nearby samples were higher than the OLS predicted and negative where they were lower. The RK surface is the sum, which has the broad shape of the OLS prediction but with local detail added by the kriged residuals.\n\nAnd the variance surface around the RK predictions:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nomHatVar_rast <- sf_2_rast(omHat_sf, variable2get = \"omModel.var\")\nomHatVar_rast <- omHatVar_rast %>% mutate(omModel.var.sqrt = sqrt(omModel.var))\nggplot() + geom_spatraster(data = omHatVar_rast,\n                           mapping = aes(fill=omModel.var.sqrt)) +\n  scale_fill_terrain_c() +\n  labs(fill = \"Organic Matter SD (%)\")\n```\n\n::: {.cell-output-display}\n![](09GeostatsRegressionKriging_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\nCompare the RK prediction surface to the OLS surface above. The overall patterns driven by distance and soil type are still there, because those came from the regression, but the spatial detail is richer because the kriged residuals filled in structure the covariates missed. Whether the added complexity translates to better predictive skill is a question for cross-validation.\n\n## Your Work\nUse `gstat.cv` to perform cross-validation on both the OLS-only model (`omGstat`) and the full RK model (`omGstat_w_variogram`). Compute RMSE and R$^2$ for each. Did RK improve the predictions over plain OLS? How much, and where do you think the improvement (or lack of it) came from?\n\n\n::: {.cell}\n\n:::\n\n",
    "supporting": [
      "09GeostatsRegressionKriging_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}