{
  "hash": "155a0f507ebf3a610c65a1ed97a2476f",
  "result": {
    "engine": "knitr",
    "markdown": "# Probabilistic Interpolation: Kriging\n\n\n\n::: {.cell}\n\n:::\n\n\n## Big Idea\nWe often want to estimate phenomena at locations where we do not have measurements. Geostatistics is the field that we use to make (hopefully) accurate and reliable models of spatial data. We will use these models for prediction. We can use both deterministic and probabilistic models. This chapter focuses on probabilistic methods. Kriging is a probabilistic method that finds spatial pattern and predicts unknown values based on that spatial pattern. Unlike IDW, kriging generates a measure of uncertainty allowing us to estimate confidence in the predictions.\n\n## Packages\nThe `gstat`[@R-gstat] package is your friend. And I'm going to plot in `ggplot` via `tidyverse`[@R-tidyverse] with `sf`[@R-sf], `terra`[@R-terra] and `tidyterra`[@R-tidyterra]. We'll also use `automap`[@R-automap] for automatic variogram fitting.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(sf)\nlibrary(gstat)\nlibrary(tidyverse)\nlibrary(terra)\nlibrary(tidyterra)\nlibrary(automap)\n```\n:::\n\n\n## Some Kriging Theory\nIDW is a deterministic interpolation method. That is, it relies on a specified mathematical formula that is not a function of the statistical relationship among the known points. This method has no error term associated with it and in fact isn't really geostatistical in a strict sense. Now, you might like to have no error in your estimation, but just because IDW doesn't spit out an error term doesn't mean that no error exists. A true geostatistical technique not only produces a prediction surface but also provides some measure of the accuracy of the predictions. Recall how the names in the IDW objects we calculated had a blank column (`var1.var`)? That's where the error surface will be in addition to the predictions (`var1.pred`) as we move forward with a probabilistic approach to interpolation called Kriging. \n\n::: {.callout-note}\nThe method is named after Danie Krige, a South African mining engineer who developed  distance-weighted averaging to estimate gold grade distributions from borehole samples at the Witwatersrand reef complex in the 1950s. The Witwatersrand Basin is the world’s largest known gold repository. The French mathematician Georges Matheron later formalized the theoretical framework in 1960. So yes, kriging started as a way to find gold. The verb is \"to krige\" and you will see it both capitalized and not in the literature -- both are fine.\n:::\n\nKriging is a geostatistical method of interpolation that uses spatial autocorrelation, and it works best when there is strong autocorrelation in the data. When kriging we use the distance between sample points (and sometimes direction) to explain variation in a variable. We then fit a mathematical model to a specified number of points (or points within a certain distance) to determine the output value for each location. \n\nThe approach makes heavy use of variograms, which we introduced in the Global Autocorrelation chapter. They are how we determine the parameter $\\lambda$ in the formula for kriging:\n\n$$\\hat{Z}(s_0)=\\sum_{i=1}^n \\lambda_i Z(s_i)$$\n\nwhere $\\hat{Z}$ will be an estimate of a variable at a spatial location $s_0$ where we haven't measured $Z$ and $s_i$ a location, $i$, where we have measured $Z$. There are $n$ measurements. Analogous to the $w$ terms for IDW, $\\lambda_i$ is a weight for the measured value at location $s_i$. With IDW the weight was a deterministic function of distance. With kriging, we use the distance between the measured points and the prediction location as well as the overall spatial structure of the measured points themselves. That spatial structure is the spatial autocorrelation measured by the variogram. Let's review variograms.\n\n## Variogram Redux\nFitting a variogram is also called structural analysis and it is where we calculate the squared difference between the values of pairs of measured points. In the variogram we set this as $\\gamma = (z_i-z_j)^2/2$. We then plot $\\gamma$ against distance and we have a variogram cloud. In practice the number of pairs (dyads) to calculate and plot gets very large. For $n$ points there are $n \\cdot (n-1) / 2$ pairs. So, instead of plotting each pair we average $\\gamma$ by distance bins. This is the empirical semivariogram.\n\nWe will demonstrate a variogram with the Meuse River data. Here we load `meuse2` (the point measurements) and `meuse.grid2` (the prediction grid), make a new variable by logging the `lead` column and plot them. This is the same setup we used in the IDW chapter. See the [appendix](A1DataSources.qmd) for details on both datasets.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load\nmeuse2 <- readRDS(\"data/meuse2.Rds\")\nmeuse.grid2 <- readRDS(\"data/meuse.grid2.Rds\")\n\n# make a variable to work with\nmeuse2$logLead <- log(meuse2$lead)\n# make into sf\nmeuseSf <- st_as_sf(meuse2, coords = c(\"x\", \"y\")) %>%\n  st_set_crs(value = 28992)\n\nmeuseGridSf <- st_as_sf(meuse.grid2,\n  coords = c(\"x\", \"y\"),\n  crs = st_crs(meuseSf)\n)\nmeuseGridSf\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 3089 features and 9 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 178500 ymin: 329660 xmax: 181500 ymax: 333700\nProjected CRS: Amersfoort / RD New\nFirst 10 features:\n   soil ffreq   elev_m slope_deg aspect_deg           tpi       twi landcover\n2     1     1 31.77303 2.9904907  298.57710  0.0103604794  6.548735        40\n3     1     1 31.48208 0.4433831   38.99447 -0.0023341179  9.436335        30\n4     1     1 31.49518 0.8556243  337.61689 -0.0021061897 10.007915        30\n5     1     1 32.66366 5.4758474  287.62243  0.0182695389  5.671510        40\n6     1     1 32.47068 1.3287795   55.89479  0.0010542870  8.017003        10\n7     1     1 31.88524 0.7232355   15.40584 -0.0040280819 12.395674        40\n8     1     1 32.36620 2.2267571  310.21836 -0.0041952133  7.633476        30\n9     1     1 33.22409 4.1998876  286.46689  0.0206255913  6.431416        40\n10    1     1 33.20650 0.8437299   61.19775  0.0001220703  8.316219        40\n11    1     1 32.86385 0.9081502   57.88412  0.0022110939  9.335344        40\n   river_dist_m              geometry\n2      47.48153 POINT (181140 333700)\n3      72.94615 POINT (181180 333700)\n4      98.41078 POINT (181220 333700)\n5      52.86416 POINT (181100 333660)\n6      78.32878 POINT (181140 333660)\n7     103.79340 POINT (181180 333660)\n8     129.25803 POINT (181220 333660)\n9      56.16095 POINT (181060 333620)\n10     83.71141 POINT (181100 333620)\n11    109.17603 POINT (181140 333620)\n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(data = meuseSf) +\n  geom_sf(aes(fill = logLead),\n    size = 4,\n    shape = 21, color = \"white\", alpha = 0.8\n  ) +\n  scale_fill_continuous(type = \"viridis\", name = \"log(ppm)\") +\n  labs(title = \"Lead concentrations\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](08GeostatsKriging_files/figure-html/meuse-data-1.png){width=672}\n:::\n:::\n\n\nWe will use the `variogram` function in `gstat`. Look back at the autocorrelation module for review as needed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nleadVar <- variogram(logLead ~ 1, meuseSf)\nplot(leadVar,\n  pch = 20, cex = 1.5, col = \"black\",\n  ylab = expression(\"Semivariance (\" * gamma * \")\"),\n  xlab = \"Distance (m)\", main = \"Lead concentrations (log(ppm))\"\n)\n```\n\n::: {.cell-output-display}\n![](08GeostatsKriging_files/figure-html/lead-variogram-1.png){width=672}\n:::\n:::\n\n\nThis is the sample, or empirical, semivariogram. We interpret it as measurements that are closer together (left on the x-axis) have similar values (low values of $\\gamma$). As we move to pairs further apart (right on the x-axis) the semivariogram increases; values are more dissimilar and thus have a higher value of $\\gamma$. Our next job is going to be to fit a model to the points on the variogram. Before we do that, let's appreciate the three terms for describing the variogram.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](08GeostatsKriging_files/figure-html/variogram-anatomy-1.png){width=672}\n:::\n:::\n\n\n* The **range** is the distance beyond which the data are no longer correlated.\n* The **sill** is the variance of the variable.\n* The **nugget** is the autocorrelation at very small scales. The nugget represents independent error, measurement error and/or micro-scale variation at fine spatial scales. In a continuous variable we would expect that the nugget effect will be zero because at distance zero the values will be the same. However some variables can change in an abrupt manner and so in very short distance there is a difference.\n* The **partial sill** is the height the curve climbs from the nugget up to the sill, so it captures just the spatially structured part of the variance, the share that autocorrelation actually explains. As far as I can tell gstat is the only place anyone insists on naming it, but here we are, dutifully calling it `psill`.\n\nIf there is no structure (no correlation) and the variable is therefore a purely random variable, the variogram will be flat with a nugget effect.\n\n## Variogram Model\n\nAfter plotting the sample variogram we can then fit a statistical model to the points. The model is a continuous estimate of $\\gamma$ as a function of distance: $\\hat{\\gamma}=f(d)$.  \n\nWe will fit two different functions, a spherical model and an exponential model. The text has descriptions of the various functions. In practice, we tend to look at the general shape of the plot and then choose a mathematical model that fits.\n\nThe code below hands `vgm` a set of starting guesses for the partial sill, range, and nugget. Why guess at all? Because fitting a variogram model isn't a one-shot calculation. `fit.variogram` uses weighted least squares to nudge the three parameters around until the model curve sits as close as it can to the empirical points, and like any iterative optimizer it has to start somewhere. We read those starting values straight off the empirical plot: the height where the points level off is roughly the sill, the distance where they flatten is roughly the range, and where the curve would meet the y-axis is roughly the nugget. Give the algorithm a sensible place to begin and it takes the fit from there.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# note our initial estimates for the partial sill, range, and nugget.\nsphericalModel <- vgm(psill = 0.5, model = \"Sph\", range = 750, nugget = 0.05)\nsphericalFit <- fit.variogram(object = leadVar, model = sphericalModel)\nsphericalFit # look at the fitted values\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  model     psill    range\n1   Nug 0.1095742    0.000\n2   Sph 0.4560318 1002.626\n```\n\n\n:::\n:::\n\n\nThis is a terrible table to look at, but it only has a few numbers in it. There are two rows because `gstat` treats the nugget and the spherical part as two separate model components stacked together. The first row, `Nug`, is the nugget: its `psill` entry (0.11) is the nugget value and its `range` is fixed at zero because a nugget has no spatial extent. The second row, `Sph`, is the spherical part: its `psill` (0.46) is the partial sill and its `range` (1003 meters) is the range. Add the two `psill` values together and you have the sill. It took me a long time to be able to parse this `gstat` output but it sort of makes sense after a while I guess.\n\nLet's look at it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(leadVar,\n  model = sphericalFit, pch = 20, cex = 1.5, col = \"black\",\n  ylab = expression(\"Semivariance (\" * gamma * \")\"),\n  xlab = \"Distance (m)\", main = \"Lead concentrations (log(ppm))\",\n  sub = \"Points: Empirical, Line: Spherical Model\"\n)\n```\n\n::: {.cell-output-display}\n![](08GeostatsKriging_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n\nWe now have a fitted, theoretical, variogram model to the data in the `sphericalFit` object. This object took our estimates of the partial sill, range, and nugget and found the best fits from those estimates using non-linear regression. The final parameters are pretty close to our estimates from the plot. E.g., the fitted nugget is 0.11 and the range is 1002.63. If we gave initial estimates way outside the realm of possibility the function wouldn't be able to fit the model. But if the data are well behaved it converges on the best fit pretty easily. If you are too scared to estimate initial values in `vgm` the function will estimate them for you. See Details under `?fit.variogram` for how those are calculated. E.g., in this application if you try `sphericalModel <- vgm(model=\"Sph\",nugget=TRUE)` the `fit.variogram` algorithm converges without initial estimates.\n\nThe actual function for the spherical model is:\n\n$$\\hat{\\gamma}(d)= b + C_0 \\left(1.5\\left(\\frac{d}{r}\\right) - 0.5 \\left(\\frac{d^3}{r^3}\\right)\\right)$$\n\nwhere $b$ is the nugget, $C_0$ is the partial sill, $d$ is the distance, and $r$ is the range. Note the $r^3$ in the denominator of the second term, not $r$. The cubic term is what gives the spherical model its characteristic shape: it rises steeply at short distances and flattens out as it approaches the sill at distance $r$, after which $\\hat{\\gamma}$ is constant.\n\nThe spherical model above is very commonly used and has nice theoretical properties, using all three classic parameters of the variogram. We could, if we liked, fit some other models. An exponential model would fit well here too. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# note our initial estimates for the sill, range, and nugget\nexponentialModel <- vgm(psill = 0.5, model = \"Exp\", range = 750, nugget = 0.05)\nexponentialFit <- fit.variogram(object = leadVar, model = exponentialModel)\nplot(leadVar,\n  model = exponentialFit, pch = 20, cex = 1.5, col = \"black\",\n  ylab = expression(\"Semivariance (\" * gamma * \")\"),\n  xlab = \"Distance (m)\", main = \"Lead concentrations (log(ppm))\",\n  sub = \"Points: Empirical, Line: Exponential Model\"\n)\n```\n\n::: {.cell-output-display}\n![](08GeostatsKriging_files/figure-html/exponential-fit-1.png){width=672}\n:::\n:::\n\n\nThis model is $\\hat{\\gamma}(d)=b + C_0(1-e^{-d/a})$ where $a=r/3$ and other terms are as above. Unlike the spherical model, the exponential never quite reaches the sill -- it approaches asymptotically. For many data sets both models fit about equally well, and choosing between them comes down to visual inspection and, ultimately, cross-validation skill.\n\n## Putting it Together\nWe have a fitted variogram model now. That is $\\hat{\\gamma}(d)$, an estimate of spatial structure at any distance. Here is our kriging formula again:\n\n$$\\hat{Z}(s_0)=\\sum_{i=1}^n \\lambda_i Z(s_i)$$\n\nHow do we get to the weights ($\\lambda$)? From the variogram model. The guts of this calculation involve a little matrix algebra to fully work through, but conceptually it is pretty simple: \n$$ \\lambda = \\Gamma^{-1} g $$\n\nwhere $\\Gamma$ is a matrix of the semivariances for all sampled point pairs, predicted as a function of their Euclidean distances using the fitted variogram model, and $g$ is a vector of predicted semivariances between the unknown point and each measured point, calculated the same way. Once we have $\\lambda$ we can interpolate (predict) over a surface for any location where we don't have $Z$.\n\n## Toy Example\nLike we did with IDW, let's walk through this calculation with a contrived example.\n\n### Data\nHere is a small data set of five points. We have spatial coordinates ($x$ and $y$) and some measured variable ($z$).\n\n::: {.cell}\n\n```{.r .cell-code}\ntoyDat <- data.frame(\n  x = c(1, 3, 1, 4, 5),\n  y = c(5, 4, 3, 5, 1),\n  z = c(100, 105, 105, 100, 115)\n)\ntoyDat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  x y   z\n1 1 5 100\n2 3 4 105\n3 1 3 105\n4 4 5 100\n5 5 1 115\n```\n\n\n:::\n\n```{.r .cell-code}\ntoyPlot <- ggplot() +\n  geom_point(data = toyDat, aes(x = x, y = y, size = z)) +\n  lims(x = c(0, 6), y = c(0, 6)) +\n  coord_equal() +\n  theme_minimal()\ntoyPlot\n```\n\n::: {.cell-output-display}\n![](08GeostatsKriging_files/figure-html/toy-data-1.png){width=480}\n:::\n:::\n\n\nLet's imagine a point $x=2$ and $y=4$ where we don't know $z$ and add that to the plot.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntoyPlot +\n  # crosshair reticle marking the location we want to predict\n  annotate(\"segment\", x = 1.4, xend = 2.6, y = 4, yend = 4, color = \"#21908C\", linewidth = 0.6) +\n  annotate(\"segment\", x = 2, xend = 2, y = 3.4, yend = 4.6, color = \"#21908C\", linewidth = 0.6) +\n  annotate(\"point\", x = 2, y = 4, shape = 1, size = 13, color = \"#21908C\", stroke = 1) +\n  annotate(\"point\", x = 2, y = 4, shape = 21, fill = \"#21908C\", color = \"white\", size = 2.5, stroke = 0.6) +\n  annotate(\"text\", x = 2.55, y = 4.6, label = \"s[0]\", parse = TRUE, color = \"#21908C\", size = 5, hjust = 0, fontface = \"italic\")\n```\n\n::: {.cell-output-display}\n![](08GeostatsKriging_files/figure-html/toy-unknown-point-1.png){width=480}\n:::\n:::\n\n\n### Interpolate with Kriging\nWe are now going to use kriging as a way to get an estimate of that point with a missing value of $z$. Since we are estimating it we call it $\\hat{Z}$ and we know the location as $s_0$ so we call this $\\hat{Z}(s_0)$. We'll follow the notation above.\n\nThe Euclidean distance to our unknown point from each of the known points is a vector: \n\n::: {.cell}\n\n:::\n\n\n$$\\mathbf{d_i} = \\left[\\begin{array}\n{rr}\n1 & 1.414\\\\\n2 & 1.000\\\\\n3 & 1.414\\\\\n4 & 2.236\\\\\n5 & 4.243\n\\end{array}\\right]$$\n\nTo get $\\hat{Z}(s_0)$ we apply $\\lambda = \\Gamma^{-1} g$ from above. Now, these five data points don't actually make a nice variogram. So let's suspend disbelief for a moment and say we fit a spherical model with nugget $= 0$, partial sill $= 10$, and range $= 6$. Those aren't fitted values from this tiny dataset, just reasonable numbers for a worked example.\n\n$$\\hat{\\gamma}(d) = 10\\left(1.5\\left(\\frac{d}{6}\\right) - 0.5\\left(\\frac{d}{6}\\right)^3\\right) \\quad \\text{for } d \\leq 6$$\n\nFirst we can calculate $g$ for the point we want to interpolate by plugging each distance $d_i$ into the variogram model:\n\n\n::: {.cell}\n\n:::\n\n\n$$\\mathbf{g} = \\left[\\begin{array}\n{rr}\n1 & 3.470\\\\\n2 & 2.477\\\\\n3 & 3.470\\\\\n4 & 5.331\\\\\n5 & 8.839\n\\end{array}\\right]$$\n\nNow, let's get $\\Gamma$. First, here is the distance matrix between all the measured points:\n\n$$\\mathbf{d} = \\left[\\begin{array}\n{rrrrr}\n~ & 1 & 2 & 3 & 4 \\\\\n2 & 2.236 & ~ & ~ & ~ \\\\\n3 & 2.000 & 2.236 & ~ & ~ \\\\\n4 & 3.000 & 1.414 & 3.606 & ~ \\\\\n5 & 5.657 & 3.606 & 4.472 & 4.123\n\\end{array}\\right]$$\n\nWe apply the same spherical variogram model to the distances between all measured points to get $\\Gamma$:\n\n\n::: {.cell}\n\n:::\n\n\n$$\\mathbf{\\Gamma} = \\left[\\begin{array}\n{rrrrr}\n~ & 1 & 2 & 3 & 4 \\\\\n2 & 5.331 & ~ & ~ & ~ \\\\\n3 & 4.815 & 5.331 & ~ & ~ \\\\\n4 & 6.875 & 3.470 & 7.929 & ~ \\\\\n5 & 9.952 & 7.929 & 9.110 & 8.685\n\\end{array}\\right]$$\n\nWe now need the inverse of $\\Gamma$. Inverting a matrix bigger than say 2x2 is not something I want to do by hand. Inverting a 5x5 matrix by hand would take me all day and I'd definitely screw it up. If you can't recall how to invert a matrix, any linear algebra text will walk you through it. In R you can use the `solve` function (or `ginv` in the `MASS` package) to invert a matrix.\n\n\n::: {.cell}\n\n:::\n\n\n$$\\mathbf{\\Gamma^{-1}} = \\left[\\begin{array}\n{rrrrr}\n~ & 1      & 2      & 3      & 4      & 5     \\\\\n1 & -0.1322 & 0.0322  & 0.0805  & 0.0376  & 0.0183  \\\\\n2 & 0.0322  & -0.2308 & 0.0547  & 0.1164  & 0.0167  \\\\\n3 & 0.0805  & 0.0547  & -0.1340 & -0.0017 & 0.0367  \\\\\n4 & 0.0376  & 0.1164  & -0.0017 & -0.1475 & 0.0404  \\\\\n5 & 0.0183  & 0.0167  & 0.0367  & 0.0404  & -0.0546\n\\end{array}\\right]$$\n\nAnd $\\lambda = \\Gamma^{-1} g$:\n$$\\mathbf{\\lambda_i} = \\left[\\begin{array}\n{rr}\n1 & 0.2626\\\\\n2 & 0.4985\\\\\n3 & 0.2652\\\\\n4 & -0.0165\\\\\n5 & -0.0353\n\\end{array}\\right]$$\n\nYou'll notice that points 4 and 5 have negative weights. With IDW, every point gets a positive weight that simply shrinks with distance. Kriging is more sophisticated: it considers the spatial structure among all the measured points at once. Points 4 and 5 are far from the prediction location, so their semivariances in $g$ are large and their influence on the prediction is already small. But they're also located in a part of the space that the closer points (1, 2, and 3) already \"cover\" informationally. The kriging system figures out that including points 4 and 5 with even a small positive weight would introduce a slight bias, so it assigns them tiny negative weights to correct for that. This is sometimes called a screening effect. The weights are small and don't change the estimate much, and it isn't a sign that something went wrong.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 100.739\n```\n\n\n:::\n:::\n\n\nGiving the final prediction:\n$$\\hat{Z}(s_0)=0.2626(100)+0.4985(105)+0.2652(105)-0.0165(100)-0.0353(115) \\approx 100.74$$\n\nThe matrix notation can be sort of tedious but hopefully you've gotten the idea: because of the theoretical variogram model we can estimate $\\hat{\\gamma}$ for any distance $d$ and use that information, along with the distance matrix among the known points, to predict $Z$ at any location.\n\n## Application: Kriging a Lead Surface\nThis will look a lot like what we did with IDW but we will use `krige` instead. And `krige` wants a fitted variogram model to be passed in. So, using the variogram from above we can do this.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nleadVar <- variogram(logLead ~ 1, meuseSf)\n# with initial gueses at the parameters psill, range, and nugget\nleadModel <- vgm(psill = 0.6, model = \"Sph\", range = 750, nugget = 0.05)\n# or try to let the estimation happen without initial guesses -- same result\nleadModel <- vgm(model = \"Sph\", nugget = TRUE)\n\nleadFit <- fit.variogram(object = leadVar, model = leadModel)\nleadGstat <- gstat(\n  formula = logLead ~ 1, locations = meuseSf,\n  model = leadFit\n)\nleadKrigeSf <- predict(leadGstat, newdata = meuseGridSf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[using ordinary kriging]\n```\n\n\n:::\n\n```{.r .cell-code}\nleadKrigeSf\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 3089 features and 2 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 178500 ymin: 329660 xmax: 181500 ymax: 333700\nProjected CRS: Amersfoort / RD New\nFirst 10 features:\n   var1.pred  var1.var              geometry\n2   5.406841 0.2724001 POINT (181140 333700)\n3   5.343480 0.2854597 POINT (181180 333700)\n4   5.279198 0.3003649 POINT (181220 333700)\n5   5.486278 0.2238744 POINT (181100 333660)\n6   5.415401 0.2377063 POINT (181140 333660)\n7   5.339935 0.2536512 POINT (181180 333660)\n8   5.266665 0.2701756 POINT (181220 333660)\n9   5.562294 0.1801611 POINT (181060 333620)\n10  5.496279 0.1894106 POINT (181100 333620)\n11  5.408148 0.2084089 POINT (181140 333620)\n```\n\n\n:::\n:::\n\n\nNote that `leadKrige` is a `sf` object that has the predicted surface `var1.pred` but there is another surface in there too, `var1.var`, which contains the variance around those predictions. Let's take a look at the predictions first and then spend some time with the variance surface.\n\nHere is the prediction surface. Note how we specify what `attribute` we want to plot via `leadKrige[\"var1.pred\"]`.\n\nI'll use the little function from the IDW chapter to get a `rast` object from the `sf` object. Remember, this is one of the reasons to write a function in the first place -- define it once, reuse it across chapters.\n\n::: {.cell}\n\n```{.r .cell-code}\nsf2Rast <- function(sfObject, variableIndex = 1) {\n  # coerce sf to a data.frame\n  dfObject <- data.frame(st_coordinates(sfObject),\n    z = as.data.frame(sfObject)[, variableIndex]\n  )\n  # coerce data.frame to SpatRaster\n  rastObject <- rast(dfObject, crs = crs(sfObject))\n\n  names(rastObject) <- names(sfObject)[variableIndex]\n\n  return(rastObject)\n}\n\nleadKrigeRast <- sf2Rast(leadKrigeSf)\n\nleadKrigeRast\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nclass       : SpatRaster\nsize        : 102, 76, 1  (nrow, ncol, nlyr)\nresolution  : 40, 40  (x, y)\nextent      : 178480, 181520, 329640, 333720  (xmin, xmax, ymin, ymax)\ncoord. ref. : Amersfoort / RD New (EPSG:28992)\nsource(s)   : memory\nname        : var1.pred\nmin value   :  3.749342\nmax value   :  6.174216\n```\n\n\n:::\n\n```{.r .cell-code}\n# and plot\nggplot() +\n  geom_spatraster(data = leadKrigeRast, mapping = aes(fill = var1.pred), alpha = 0.8) +\n  scale_fill_continuous(type = \"viridis\", name = \"log(ppm)\", na.value = \"transparent\") +\n  labs(title = \"Lead concentrations\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](08GeostatsKriging_files/figure-html/lead-krige-surface-1.png){width=672}\n:::\n:::\n\n\n\nNow let's look at the variance around those predictions. Note we take the square root of `var1.var` to get the uncertainty in the same units as `var1.pred`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nleadKrigeSf$var1.var.sqrt <- sqrt(leadKrigeSf$var1.var)\n\nleadKrigeRast <- sf2Rast(leadKrigeSf, variableIndex = 4)\nleadKrigeRast\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nclass       : SpatRaster\nsize        : 102, 76, 1  (nrow, ncol, nlyr)\nresolution  : 40, 40  (x, y)\nextent      : 178480, 181520, 329640, 333720  (xmin, xmax, ymin, ymax)\ncoord. ref. : Amersfoort / RD New (EPSG:28992)\nsource(s)   : memory\nname        : var1.var.sqrt\nmin value   :      0.388124\nmax value   :      0.650392\n```\n\n\n:::\n\n```{.r .cell-code}\n# and plot\nggplot() +\n  geom_spatraster(data = leadKrigeRast, mapping = aes(fill = var1.var.sqrt), alpha = 0.8) +\n  scale_fill_continuous(type = \"viridis\", name = \"log(ppm)\", na.value = \"transparent\") +\n  labs(title = \"Variance of lead concentrations\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](08GeostatsKriging_files/figure-html/lead-krige-variance-1.png){width=672}\n:::\n:::\n\n\nLook at the spatial pattern in that variance surface. Uncertainty is lowest near the measured points and highest at the edges of the study area where observations are sparse or absent. Compare this to the locations of your sample points in `meuseSf` and you should see the correspondence pretty clearly. This is one of the most useful things kriging gives you: not just a prediction surface, but a map of where you should trust that surface and where you should be skeptical. IDW (and TPS) will happily interpolate across a data gap without telling you it's doing so. The variance in kriging helps flag weak areas of the surface.\n\n## Uncertainty\nThe variance surface is more than just a map of sample density, though sample density is a big driver of it. The variogram models we've been fitting (spherical, exponential, and others) are more than pretty lines we use to get a continuous estimate of $\\hat{\\gamma}$ as a function of distance. They have some of the same properties as statistical distributions do in probability theory. In particular, variograms are empirical estimates of the covariance of Gaussian processes. Because the model variogram gives the mean squared difference between values based on their location, we can use it to derive the uncertainty around each prediction. The variance at any prediction location is a function of how well that location is \"covered\" by the surrounding observations, weighted by the fitted spatial covariance structure.\n\nWhat this means practically is that kriging variance increases when (a) the prediction location is far from any measured points, (b) the measured points nearby are themselves clustered rather than well-spread, and (c) the sill of the variogram is large, meaning the variable is highly variable across the study area. At very large distances from all data, the variance approaches the sill -- which is your best estimate of how variable the field is when you have no local information at all.\n\nThe underlying theory goes deeper than we will cover here. Diggle's \"Model-based Geostatistics\" will drag you through it if you want. Bivand's chapter has more on this too. I walk through it in the [Kriging Variance By Hand aside](08xAsideGeostatsKrigingVariance.html).\n\n## Other Variogram Models\nAbove I showed you the spherical and the exponential variogram models. Those are commonly used, as are the Gaussian and the Matérn models. But there are many other options -- a whole slew, actually, most of which I've never used. Look at this:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvgm()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   short                                      long\n1    Nug                              Nug (nugget)\n2    Exp                         Exp (exponential)\n3    Sph                           Sph (spherical)\n4    Gau                            Gau (gaussian)\n5    Exc        Exclass (Exponential class/stable)\n6    Mat                              Mat (Matern)\n7    Ste Mat (Matern, M. Stein's parameterization)\n8    Cir                            Cir (circular)\n9    Lin                              Lin (linear)\n10   Bes                              Bes (bessel)\n11   Pen                      Pen (pentaspherical)\n12   Per                            Per (periodic)\n13   Wav                                Wav (wave)\n14   Hol                                Hol (hole)\n15   Log                         Log (logarithmic)\n16   Pow                               Pow (power)\n17   Spl                              Spl (spline)\n18   Leg                            Leg (Legendre)\n19   Err                   Err (Measurement error)\n20   Int                           Int (Intercept)\n```\n\n\n:::\n:::\n\n\n`gstat` knows 20 different possible curves you can fit to your data. E.g.,\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshow.vgms(models = c(\"Exp\", \"Mat\", \"Gau\", \"Sph\"))\n```\n\n::: {.cell-output-display}\n![](08GeostatsKriging_files/figure-html/show-vgms-1.png){width=864}\n:::\n:::\n\n\nThe four models plotted above give you a sense of why the choice matters. The spherical model reaches the sill at a finite distance and stays there, which is appropriate when you believe the variable has a well-defined correlation length. The exponential model approaches the sill asymptotically, implying some small correlation at any distance, which suits variables that never fully decorrelate. The Gaussian model has an S-shaped approach to the sill and goes to zero slope at the origin, which implies a very smooth, continuous underlying process. The Matérn family includes both of those as special cases and is more flexible, at the cost of one extra parameter.\n\nIn practice, a few things constrain which models are valid at all. The variogram must be non-negative everywhere, and it must produce a covariance matrix that is positive semi-definite (that is matrix-speak for \"the variances this system produces can never come out negative.\"). That second condition is what makes the kriging system solvable and ensures the predicted variances come out non-negative. This is why you can't just draw any curve through the empirical variogram and call it a model. The parametric families in `gstat` all satisfy these conditions by construction, which is a good reason to stick with them rather than trying to invent your own.\n\nBeyond that, choosing among the valid options comes down to looking at the empirical variogram, thinking about the physical process you're modeling, and comparing cross-validation skill. There is no one-size-fits-all approach.\n\n## Other Types of Kriging\n\nEverything we have done in this chapter is ordinary kriging (OK), which is what `krige` does when you write `formula = logLead~1`. The `~1` means \"intercept only\" -- no covariates, just estimate the mean from the data and let the variogram do the rest. It is the right default for most situations, but it is worth knowing what else is out there.\n\n**Simple kriging (SK)** assumes the mean of the process is known rather than estimated from the data. In practice that assumption is almost never defensible, so SK sees limited use outside of simulation studies and textbooks. If you are curious how the math differs from OK, the [Kriging Variance By Hand aside](08xAsideGeostatsKrigingVariance.html) works through both side by side. In `gstat` you get SK by passing `beta = mean(dat$z)` to `krige`.\n\n**Universal kriging (UK)** and **regression kriging (RK)** both handle the situation where your response variable has a large-scale spatial trend driven by covariates, elevation gradients, distance-to-river effects, and so on. OK assumes the mean is constant across the study area (stationarity). If that assumption is badly violated, OK will struggle. UK folds the trend and the spatial structure into one system of equations. RK does it in two steps: fit an OLS regression on covariates first, then krige the residuals. The two approaches tend to give similar predictions in practice, but RK lets you inspect each step separately, which is usually worth the trouble. We cover RK in the next module. In `gstat`, UK looks like `formula = logLead~dist`, where `dist` is a covariate available at both your sample points and your prediction grid.\n\n**Anisotropic kriging** relaxes the assumption that spatial correlation is the same in all directions. If your variable has stronger autocorrelation along a river valley than across it, for example, a standard isotropic variogram will misrepresent that structure. You can model anisotropy by fitting an elliptical rather than circular variogram, via the `anis` argument to `vgm`. It adds complexity and you need enough data to justify it, but for strongly directional processes it can matter.\n\nYou could spend a whole semester on kriging alone. Think of the pleasures involved!\n\n## Cross Validation\nThe IDW chapter showed an example of using the built-in cross validation function. We can do the same with kriging. Instead of a straight call to `krige` we can call `krige.cv` for either k-fold or leave-one-out cross validation (LOOCV). It defaults to LOOCV so the predicted values are from the time they were left out the model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nleadKrigeLOOCVSf <- krige.cv(\n  formula = logLead ~ 1,\n  locations = meuseSf,\n  model = leadFit, verbose = FALSE\n)\nleadKrigeLOOCVSf\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 164 features and 6 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 178605 ymin: 329714 xmax: 181390 ymax: 333611\nProjected CRS: Amersfoort / RD New\nFirst 10 features:\n   var1.pred  var1.var observed    residual       zscore fold\n1   5.402571 0.2277973 5.700444  0.29787270  0.624103170    1\n2   5.473044 0.2199374 5.624018  0.15097361  0.321922586    2\n3   5.233697 0.2180910 5.293305  0.05960821  0.127640125    3\n4   5.077189 0.2520550 4.753590 -0.32359848 -0.644553277    4\n5   4.794539 0.2134651 4.762174 -0.03236554 -0.070051822    5\n6   4.584552 0.2571416 4.919981  0.33542860  0.661475719    6\n7   4.970576 0.2088842 4.882802 -0.08777385 -0.192049137    7\n8   5.253444 0.2072102 5.010635 -0.24280892 -0.533407471    8\n9   4.886148 0.1786532 4.890349  0.00420153  0.009940359    9\n10  4.589513 0.1984181 4.382027 -0.20748612 -0.465798826   10\n                geometry\n1  POINT (181072 333611)\n2  POINT (181025 333558)\n3  POINT (181165 333537)\n4  POINT (181298 333484)\n5  POINT (181307 333330)\n6  POINT (181390 333260)\n7  POINT (181165 333370)\n8  POINT (181027 333363)\n9  POINT (181060 333231)\n10 POINT (181232 333168)\n```\n\n\n:::\n\n```{.r .cell-code}\n# CV R2 and RMSE\nrsq <- cor(leadKrigeLOOCVSf$observed, leadKrigeLOOCVSf$var1.pred)^2\nrmse <- sqrt(mean((leadKrigeLOOCVSf$observed - leadKrigeLOOCVSf$var1.pred)^2))\nc(rsq = rsq, rmse = rmse)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      rsq      rmse \n0.6192935 0.4141229 \n```\n\n\n:::\n:::\n\n\nThe LOOCV R$^2$ is 0.619 and the RMSE is 0.414 which we get from the observed vs predicted values. But note all the fields we get from the `krige.cv` function. We get the prediction and prediction variance of the cross-validated data points and we also get the observed values. We also get the residuals (observed minus predicted), the z-score (the residual divided by kriging standard error), and the fold (in this case we have as many folds as rows in meuse because it is LOOCV).\n\n## Automap\n\nYou'll find it anyway, so let's get the cat out of the bag.\n\nLike other angry old men, I like to describe a bucolic youth spent milking at 4AM, walking to school in the snow, programming F77 in vi, and **doing all my GIS with Arc on the command line**. Kids these days like to do their geostatistics in ArcGIS by clicking \"next, next, next, finish\" and plotting their map without `ARCPLOT`. One of the many reasons I like using R is that you get to do things like fit variograms by hand the same way the pioneers did when they had to cross the prairie. But you can, if you like, automatically fit a variogram using the `automap` library which has a lot of nice wrappers for the `gstat` functions like `fit.variogram`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nleadVar <- autofitVariogram(formula = logLead ~ 1, input_data = meuseSf)\nsummary(leadVar)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nExperimental variogram:\n     np       dist     gamma dir.hor dir.ver   id\n1    17   59.33470 0.1270576       0       0 var1\n2    39   86.73182 0.1905754       0       0 var1\n3   126  130.83058 0.1487020       0       0 var1\n4   171  176.60188 0.2540911       0       0 var1\n5   198  226.70319 0.2378083       0       0 var1\n6   810  338.36102 0.3395189       0       0 var1\n7   957  502.89504 0.4191339       0       0 var1\n8  1580  712.92647 0.5180130       0       0 var1\n9  1500  961.00617 0.5738388       0       0 var1\n10 1301 1212.86100 0.5675023       0       0 var1\n11 1517 1504.85947 0.4954516       0       0 var1\n\nFitted variogram model:\n  model      psill    range\n1   Nug 0.09182989   0.0000\n2   Sph 0.46323373 941.6887\nSums of squares betw. var. model and sample var.[1] 2.920612e-05\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(leadVar)\n```\n\n::: {.cell-output-display}\n![](08GeostatsKriging_files/figure-html/automap-variogram-1.png){width=672}\n:::\n:::\n\n\nThis automatically fits and plots a variogram like `fit.variogram` but instead of using user-supplied initial estimates for the model and the parameters, `autofitVariogram` makes these estimates based on the data and then calls `fit.variogram`. The automatic fitting above chose a spherical model like we did above but it tried all the models (exponential, Gaussian, Matérn, etc.) as part of the process.\n\nThe biggest difference is that `autofitVariogram` does the bins quite differently than `gstat`'s default behavior with `variogram`. Instead of equal widths, `autofitVariogram` creates bins of unequal widths. It passes these as the `boundaries` argument to `variogram`. You can look at the code for details (`getAnywhere(autofitVariogram)`) but the spirit is to try to get more leverage on the shortest distances to help estimate the wiggliest part of the variogram curve, especially the nugget. I think it makes sense.\n\nNote that this plot (which is invoked for objects of class `autofitVariogram`) plots the number of point pairs at that distance as well as adds the model terms as a legend. You can look at the code for this plot via `getAnywhere(plot.autofitVariogram)` if you are curious.\n\nAnd just to complete the whole automation thing, you can automatically apply cross validation as well. Since `autoKrige.cv` calls `krige.cv` to do a lot of the work, it defaults to LOOCV as above.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nleadAutoKrigeLOOCV <- autoKrige.cv(\n  formula = logLead ~ 1, input_data = meuseSf,\n  verbose = c(FALSE, FALSE)\n)\nsummary(leadAutoKrigeLOOCV)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            [,1]      \nmean_error  -0.002369 \nme_mean     -0.0004967\nMAE         0.2996    \nMSE         0.1692    \nMSNE        0.8531    \ncor_obspred 0.7901    \ncor_predres 0.04327   \nRMSE        0.4113    \nRMSE_sd     0.6117    \nURMSE       0.4113    \niqr         0.4022    \n```\n\n\n:::\n\n```{.r .cell-code}\n# R2\ncor(leadAutoKrigeLOOCV$krige.cv_output$observed, leadAutoKrigeLOOCV$krige.cv_output$var1.pred)^2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6242166\n```\n\n\n:::\n:::\n\n\nHere we get a LOOCV R$^2$ of 0.6242 which is very (very) close to what we got with the cross validation we did manually above.\n\n**Use the tools in `automap` with caution however. Beware the black box.**\n\n## Wrapping Up\n\nRecall that IDW and TPS gave us a prediction surface with no uncertainty attached. Every grid cell got a number and that was that. Kriging gives us the same prediction surface, but also the variance surface we just looked at, and that second surface is where probability theory earns its keep. Imagine you're deciding where to put additional soil sampling stations to reduce uncertainty in your lead concentration map. With IDW you have no principled way to answer that question, because IDW has no model of uncertainty to begin with. With kriging, you look at the variance surface and put your next sample where the variance is highest. Or imagine you need to flag grid cells where the predicted lead concentration exceeds a regulatory threshold: with a variance surface you can attach a probability to that exceedance rather than just a point estimate. The deterministic methods we covered earlier are fast and intuitive, but they borrow nothing from probability theory, so there is no statistically grounded way to quantify how much you should trust the predictions. Kriging trades some of that simplicity for something useful: a map of your own ignorance.\n\n## Exercises\n\nReturn to the California precipitation data from the IDW chapter. This time, krige the surface rather than use IDW.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# precip point data\nprcpCA <- readRDS(\"data/prcpCA.rds\")\n# empty grid to interpolate into\ngridCA <- readRDS(\"data/gridCA.rds\")\n\nprcpCAsf <- prcpCA %>%\n  st_as_sf(coords = c(\"X\", \"Y\")) %>%\n  st_set_crs(value = 3310)\n\nprcpCAsf %>% ggplot() +\n  geom_sf(aes(fill = ANNUAL, size = ANNUAL),\n    color = \"white\",\n    shape = 21, alpha = 0.8\n  ) +\n  scale_fill_continuous(type = \"viridis\", name = \"mm\") +\n  labs(title = \"Total Annual Precipitation\") +\n  scale_size(guide = \"none\")\n```\n\n::: {.cell-output-display}\n![](08GeostatsKriging_files/figure-html/exercise-data-1.png){width=672}\n:::\n:::\n\n\nFit the variogram manually using `variogram`, `vgm`, and `fit.variogram` -- skip `automap` for this one. Compare at least two variogram models. Assess the surface using cross-validation and interpret what you find. How does the kriged surface compare to the IDW surface you made earlier? Does the kriging variance surface (`var1.var`) tell you anything useful about where you should trust the predictions?\n\n\n## Further Reading\n\n@bivand2008geostatistics chapter 8, sections 8.4 and 8.5, covers kriging theory and implementation in R in detail. @fortin2016spatial sections 4.3 to 4.5 provide a more accessible treatment of the same material. Both are worth having at hand when fitting variograms for the first time.\n",
    "supporting": [
      "08GeostatsKriging_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}