project:
  type: book
  output-dir: docs
  pre-render: Rscript purl_all.R

book:
  title: "Applied Spatial Analysis for Environmental Science"
  subtitle: "An R-Based Introduction"
  author: "Andy Bunn"
  date: today
  description: "An applied introduction to spatial analysis for environmental scientists using R"
  navbar:
    background: dark
    search: true
  chapters:
    - file: index.qmd
      text: "Cover"
    - 00Preface.qmd
    - part: "Foundations"
      chapters:
        - 01Welcome.qmd
        - 02SpatialCrashCourse.qmd
        - 02xAsideMethodsAndGenerics.qmd
    - part: "Point Patterns & Autocorrelation"
      chapters:
        - 03Point_Patterns.qmd
        - 03xAsideDistanceMatrices.qmd
        - 04GlobalAutocorrelation.qmd
        - 04xAsideCorrelationVersusRegression.qmd
        - 05LISA.qmd
    - part: "Interpolation & Geostatistics"
      chapters:
        - 06GeostatsIDW.qmd
        - 06xAsideModelSkill.qmd
        - 07Geostat2TPS.qmd
        - 08GeostatsKriging.qmd
        - 08xAsideGeostatsKrigingVariance.qmd
        - 09GeostatsRegressionKriging.qmd
        - 09xAsidePredictingNewData.qmd
    - part: "Regression"
      chapters:
        - 10RegressionGLS.qmd
        - 10xAsideOLS-Algebra-Matrix.qmd
        - 11SpatialRegressionSAR.qmd
    - 12Conclusion.qmd
    - 13References.qmd
    - part: "Appendices"
      chapters:
        - A1MeuseData.qmd
  repo-url: https://github.com/AndyBunn/spatialNotes
  repo-actions: [edit, issue]

bibliography:
  - packages.bib
  - other.bib

reference-location: document

format:
  html:
    theme: cosmo
    css: custom.css
    code-fold: show
    toc: true
    toc-depth: 4
    number-sections: false

execute:
  warning: false
  message: false
  freeze: auto