{
  "hash": "b4bbfe53ec98fcbd928f1a9b6292d934",
  "result": {
    "engine": "knitr",
    "markdown": "# Spatial Regression: Lag and Error Models\n\n\n\n## Big Idea\n\nThe GLS chapter gave us one tool for handling spatially autocorrelated residuals: specify the correlation structure with a variogram and let GLS down-weight correlated observations. That works well. But there is a whole family of spatial regression models that take a different approach, and understanding them will round out your toolkit and sharpen your thinking about what spatial structure in a regression actually means.\n\nGLS models the error correlation structure using a variogram -- a continuous function of distance. The SAR (Simultaneous AutoRegressive) family instead uses an explicit spatial weights matrix: the same neighbor structure you built for Moran's I and LISA. Two SAR models matter most for applied environmental work. The spatial error model says that the errors -- the stuff your predictors don't explain -- are spatially correlated via a neighbor process. The spatial lag model says something more provocative: that the response variable at each location is directly influenced by the response at neighboring locations. These two models answer different questions, and it matters which one you fit.\n\n::: {.callout-note}\nThis module follows directly from the [Regression: GLS](10RegressionGLS.html) chapter and assumes you are comfortable with the OLS-to-GLS workflow there. The spatial weights machinery is the same as in the [LISA](05LISA.html) chapter.\n:::\n\n## Packages\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(spatialreg)\nlibrary(spdep)\nlibrary(sf)\nlibrary(tidyverse)\n```\n:::\n\n\n`spatialreg` [@spatialreg2021] carries the main functions for fitting SAR models. It was spun off from `spdep` [@R-spdep] a few years ago, which means older code you find online might load these functions from `spdep` directly. If you see `spdep::lagsarlm()` in old tutorials, that is the same function. Load `spatialreg` explicitly. We also use `sf` [@R-sf] for spatial data structures and `tidyverse` [@R-tidyverse] for data wrangling.\n\n## Two Models, Two Questions\n\nLet's be concrete about what these models actually say.\n\nA note on notation before we dive in. In what follows, $\\mathbf{y}$ is a vector of $n$ response values (one per location), $\\mathbf{X}$ is the design matrix, $\\boldsymbol{\\beta}$ is the vector of regression coefficients, and $\\mathbf{W}$ is the spatial weights matrix you already know from Moran's I and LISA. The operation $\\mathbf{W}\\mathbf{y}$ computes a weighted average of $y$ at neighboring locations -- that is the spatial lag.\n\nYou will also notice that the same Greek letters appear here with different meanings than they had in earlier chapters. In the kriging chapter, $\\lambda$ was the vector of interpolation weights. Here it is a scalar measuring how strongly errors are correlated across neighbors. In the GLS chapter, $\\rho$ appeared in the code as the parameter we used to generate autocorrelated errors. Here $\\rho$ is the spatial autoregression coefficient on the response itself. This is not a conspiracy. Notation is there to serve the math, not to rule it, and the same letters get recycled constantly across fields, papers, and packages. Treat each symbol as local to what you are reading.\n\n**Spatial error model (SEM):**\n\n$$\\mathbf{y} = \\mathbf{X}\\boldsymbol{\\beta} + \\mathbf{u}, \\quad \\mathbf{u} = \\lambda \\mathbf{W} \\mathbf{u} + \\boldsymbol{\\varepsilon}$$\n\nThe residuals $\\mathbf{u}$ follow a spatial autoregressive process. A residual at location $i$ is a function of the residuals at its neighbors (via $\\lambda \\mathbf{W}$) plus independent noise $\\boldsymbol{\\varepsilon}$. The coefficient $\\lambda$ (lambda) captures how strongly residuals are autocorrelated across neighbors. The coefficients $\\boldsymbol{\\beta}$ have the same interpretation as in OLS: a one-unit increase in $x$ is associated with a $\\beta_1$ change in $y$, on average, holding everything else constant.\n\nEcologically, the SEM is the right choice when space is a nuisance. Your predictors don't capture all the spatial structure in $y$, so the leftovers are autocorrelated. Classic example: you're modeling tree growth as a function of soil nitrogen, but soil moisture, microclimate, and a dozen other unmeasured things also drive growth and are themselves spatially structured. The SEM absorbs that shared unmeasured spatial structure into the error term and gives you clean, valid inference on the nitrogen-growth relationship.\n\n**Spatial lag model (SLM):**\n\n$$\\mathbf{y} = \\rho \\mathbf{W} \\mathbf{y} + \\mathbf{X}\\boldsymbol{\\beta} + \\boldsymbol{\\varepsilon}$$\n\nNow the response variable $\\mathbf{y}$ at each location appears on both sides of the equation. It is a function of $\\mathbf{W}\\mathbf{y}$ -- the weighted average of $y$ at neighboring locations -- plus your predictors $\\mathbf{X}$ and independent noise $\\boldsymbol{\\varepsilon}$. The coefficient $\\rho$ (rho) is a scalar that captures how strongly $y$ at one location is pulled toward $y$ at its neighbors.\n\nThis is a fundamentally different claim from the SEM. The SLM says there is a spatial spillover process: $y$ at one location influences $y$ at neighboring locations. Classic examples are disease spread (infection rate in one area influences neighboring areas), invasive species dispersal (abundance at one site drives colonization of nearby sites), or any system where diffusion, movement, or social contagion is part of the process. If the biology or ecology predicts that kind of mechanism, the lag model is the one to reach for.\n\nOne important caution: the $\\boldsymbol{\\beta}$ coefficients from the SLM are not total marginal effects. More on this below.\n\n## Choosing Between Them: LM Tests\n\nThere is a diagnostic test for choosing the appropriate model. The Rao score tests in `spdep::lm.RStests()` take an OLS fit and a weights matrix and test for evidence of spatial error vs spatial lag structure in the residuals. You get five test statistics from `test = \"all\"`:\n\n- **RSerr**: tests for spatial error autocorrelation. Significant means the error model looks useful.\n- **RSlag**: tests for spatial lag structure. Significant means the lag model looks useful.\n- **adjRSerr**: robust test for error, controlling for the possibility of a lag. Use this when both RSerr and RSlag are significant.\n- **adjRSlag**: robust test for lag, controlling for error structure. Same situation.\n- **SARMA**: joint test for both.\n\nThe decision tree is simple. If only one of RSerr or RSlag is significant, fit that model. If both are significant, look at the robust tests and fit whichever of adjRSerr or adjRSlag is more significant. If neither is significant, OLS is fine.\n\n## Toy Example\n\nWe will build simulated data following the same spirit as the GLS chapter: a response $y$ that is a function of $x$ with spatially autocorrelated errors. We know going in that the spatial error model is the right answer. We will run the LM tests, confirm they point to the error model, and then fit both models to see what each gives us.\n\n### Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- 75\neasting <- runif(n, 0, 100)\nnorthing <- runif(n, 0, 100)\npoints <- cbind(easting, northing)\n\n# Build spatially autocorrelated errors via a SAR process\ndnb <- dnearneigh(x = points, d1 = 0, d2 = 150)\ndsts <- nbdists(nb = dnb, coords = points)\np <- 2.25\nidw <- lapply(dsts, function(x) x^-p)\nwList <- nb2listw(neighbours = dnb, glist = idw, style = \"W\")\n\ninv <- spatialreg::invIrW(x = wList, rho = 0.75)\nepsilon <- inv %*% rnorm(n)\nepsilon <- scale(epsilon[, 1])[, 1]\n\n# Response variable: y is a function of x plus autocorrelated noise\nx <- rnorm(n)\nB0 <- 3\nB1 <- 0.5\ny <- B0 + B1 * x + epsilon\n\ndat <- data.frame(easting, northing, y, x)\n```\n:::\n\n\nWe also need a k-nearest-neighbor weights matrix for the SAR models. Same approach as the LISA chapter.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnbK8 <- knn2nb(knearneigh(points, k = 8))\nW <- nb2listw(nbK8, style = \"W\")\n```\n:::\n\n\n### OLS and Residual Check\n\nStart with OLS.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nols <- lm(y ~ x, data = dat)\ndat$olsResids <- residuals(ols)\nmoran.test(dat$olsResids, W)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMoran I test under randomisation\n\ndata:  dat$olsResids  \nweights: W    \n\nMoran I statistic standard deviate = 7.0468, p-value = 9.152e-13\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n      0.343949179      -0.013513514       0.002573207 \n```\n\n\n:::\n:::\n\n\nMoran's I is significantly positive on the OLS residuals. We know we have a problem. Run the LM tests.\n\n### LM Tests\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm.RStests(ols, listw = W, test = \"all\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tRao's score (a.k.a Lagrange multiplier) diagnostics for spatial\n\tdependence\n\ndata:  \nmodel: lm(formula = y ~ x, data = dat)\ntest weights: W\n\nRSerr = 39.288, df = 1, p-value = 3.657e-10\n\n\n\tRao's score (a.k.a Lagrange multiplier) diagnostics for spatial\n\tdependence\n\ndata:  \nmodel: lm(formula = y ~ x, data = dat)\ntest weights: W\n\nRSlag = 31.251, df = 1, p-value = 2.267e-08\n\n\n\tRao's score (a.k.a Lagrange multiplier) diagnostics for spatial\n\tdependence\n\ndata:  \nmodel: lm(formula = y ~ x, data = dat)\ntest weights: W\n\nadjRSerr = 8.5111, df = 1, p-value = 0.00353\n\n\n\tRao's score (a.k.a Lagrange multiplier) diagnostics for spatial\n\tdependence\n\ndata:  \nmodel: lm(formula = y ~ x, data = dat)\ntest weights: W\n\nadjRSlag = 0.47438, df = 1, p-value = 0.491\n\n\n\tRao's score (a.k.a Lagrange multiplier) diagnostics for spatial\n\tdependence\n\ndata:  \nmodel: lm(formula = y ~ x, data = dat)\ntest weights: W\n\nSARMA = 39.763, df = 2, p-value = 2.321e-09\n```\n\n\n:::\n:::\n\n\nBoth RSerr and RSlag will be significant -- a spatial error process can produce apparent lag structure because the autocorrelated errors bleed into the response. Look at the robust tests. adjRSerr is significant; adjRSlag is not. That points to the error model, which is the right answer since that is how we built the data.\n\n### Spatial Error Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsemFit <- errorsarlm(y ~ x, data = dat, listw = W)\nsummary(semFit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:errorsarlm(formula = y ~ x, data = dat, listw = W)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-1.832670 -0.516352 -0.011576  0.503105  2.692372 \n\nType: error \nCoefficients: (asymptotic standard errors) \n            Estimate Std. Error z value  Pr(>|z|)\n(Intercept) 3.096759   0.336247  9.2098 < 2.2e-16\nx           0.482327   0.086319  5.5877 2.301e-08\n\nLambda: 0.72049, LR test value: 23.41, p-value: 1.3092e-06\nAsymptotic standard error: 0.10165\n    z-value: 7.0877, p-value: 1.3636e-12\nWald statistic: 50.235, p-value: 1.3636e-12\n\nLog likelihood: -94.04644 for error model\nML residual variance (sigma squared): 0.66157, (sigma: 0.81337)\nNumber of observations: 75 \nNumber of parameters estimated: 4 \nAIC: 196.09, (AIC for lm: 217.5)\n```\n\n\n:::\n:::\n\n\nThe coefficient table gives $\\hat\\beta_0$ and $\\hat\\beta_1$, interpreted exactly like OLS coefficients. The additional parameter is $\\lambda$, the spatial autocorrelation in the errors. A value near 1 means strong spatial error dependence; near 0 means the error model adds little over OLS. Given how we generated the data ($\\rho = 0.75$), lambda should be substantial, and the coefficient estimates should land near our known values of $\\beta_0 = 3$ and $\\beta_1 = 0.5$.\n\nCheck the residuals.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat$semResids <- residuals(semFit)\nmoran.test(dat$semResids, W)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMoran I test under randomisation\n\ndata:  dat$semResids  \nweights: W    \n\nMoran I statistic standard deviate = 1.0261, p-value = 0.1524\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n      0.038829368      -0.013513514       0.002601947 \n```\n\n\n:::\n:::\n\n\nMoran's I on the SEM residuals should be near zero. The spatial structure has been absorbed into $\\lambda$ and what is left looks like independent noise.\n\n### Spatial Lag Model\n\nFor comparison, fit the lag model on the same data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nslmFit <- lagsarlm(y ~ x, data = dat, listw = W)\nsummary(slmFit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:lagsarlm(formula = y ~ x, data = dat, listw = W)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-2.068155 -0.557181  0.051375  0.542870  2.708741 \n\nType: lag \nCoefficients: (asymptotic standard errors) \n            Estimate Std. Error z value  Pr(>|z|)\n(Intercept)  1.14051    0.38178  2.9874  0.002814\nx            0.43158    0.09069  4.7589 1.947e-06\n\nRho: 0.62184, LR test value: 18.187, p-value: 2.0028e-05\nAsymptotic standard error: 0.11873\n    z-value: 5.2375, p-value: 1.6276e-07\nWald statistic: 27.431, p-value: 1.6276e-07\n\nLog likelihood: -96.65795 for lag model\nML residual variance (sigma squared): 0.72882, (sigma: 0.85371)\nNumber of observations: 75 \nNumber of parameters estimated: 4 \nAIC: 201.32, (AIC for lm: 217.5)\nLM test for residual autocorrelation\ntest value: 10.136, p-value: 0.0014539\n```\n\n\n:::\n:::\n\n\nThe lag model estimates $\\rho$, the spatial autoregression of the response. Because the data were generated under an error process, this is the wrong model. It fits reasonably (the models are related) but the LM tests already pointed us elsewhere, and the AIC confirms it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nAIC(semFit, slmFit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       df      AIC\nsemFit  4 196.0929\nslmFit  4 201.3159\n```\n\n\n:::\n:::\n\n\nThe SEM should win. This is a good workflow to internalize: LM tests first, then model fitting, then AIC as a sanity check.\n\nNow let's run this on data we didn't build.\n\n## Bird Species Richness in Mexico\n\nThe `birdRichnessMexico` dataset has 200 point locations across Mexico with bird species richness (`nSpecies`) and six WorldClim bioclimatic variables extracted at each location. Maps use `tmap` [@tmap2018]. Two predictors have strong ecological justification: mean annual precipitation (`map`) and temperature annual range (`tempRange`). Wetter areas support more species; thermally variable areas support fewer. That's the energy-water hypothesis and Rapoport's rule operating across the Mexican landscape.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tmap)\nbirdsSf <- readRDS(\"data/birdRichnessMexico.rds\")\ncoordsBirds <- st_coordinates(birdsSf)\n\nnbBirds <- knn2nb(knearneigh(coordsBirds, k = 8))\nWBirds <- nb2listw(nbBirds, style = \"W\")\n```\n:::\n\n\nMap the richness surface first.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\ntm_shape(birdsSf) +\n  tm_symbols(\n    col = \"nSpecies\", palette = \"viridis\",\n    title.col = \"Species\", size = 0.4\n  )\n```\n\n::: {.cell-output-display}\n![](11SpatialRegressionSAR_files/figure-html/bird-richness-map-1.png){width=672}\n:::\n:::\n\n\n### OLS and Residual Check\n\n\n::: {.cell}\n\n```{.r .cell-code}\nolsBirds <- lm(nSpecies ~ map + tempRange, data = birdsSf)\nsummary(olsBirds)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = nSpecies ~ map + tempRange, data = birdsSf)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-136.424  -13.629   -2.138   15.146   92.269 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 213.383856  15.079562  14.151  < 2e-16 ***\nmap           0.078438   0.004528  17.324  < 2e-16 ***\ntempRange    -1.758331   0.473349  -3.715 0.000265 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 27.74 on 197 degrees of freedom\nMultiple R-squared:  0.8009,\tAdjusted R-squared:  0.7989 \nF-statistic: 396.3 on 2 and 197 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n$R^2$ of 0.80. Both predictors are significant with the expected signs. Now check the residuals.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbirdsSf$ols_resids <- residuals(olsBirds)\nmoran.test(birdsSf$ols_resids, WBirds)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMoran I test under randomisation\n\ndata:  birdsSf$ols_resids  \nweights: WBirds    \n\nMoran I statistic standard deviate = 12.42, p-value < 2.2e-16\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n      0.397871539      -0.005025126       0.001052372 \n```\n\n\n:::\n:::\n\n\nMoran's I is 0.40, strongly significant. The model explains 80% of the variance but the residuals carry substantial spatial signal. Map them to see where the model is over- and under-predicting.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(birdsSf) +\n  tm_symbols(\n    col = \"ols_resids\",\n    palette = \"-RdBu\",\n    midpoint = 0,\n    title.col = \"Residual\",\n    size = 0.4\n  )\n```\n\n::: {.cell-output-display}\n![](11SpatialRegressionSAR_files/figure-html/bird-resid-map-1.png){width=672}\n:::\n:::\n\n\nThe pattern is not random. There are regions where richness is consistently higher than the climate model predicts and others where it's consistently lower. That's what Moran's I is flagging, and the map shows you where.\n\n### LM Tests\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm.RStests(olsBirds, listw = WBirds, test = \"all\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tRao's score (a.k.a Lagrange multiplier) diagnostics for spatial\n\tdependence\n\ndata:  \nmodel: lm(formula = nSpecies ~ map + tempRange, data = birdsSf)\ntest weights: WBirds\n\nRSerr = 140.81, df = 1, p-value < 2.2e-16\n\n\n\tRao's score (a.k.a Lagrange multiplier) diagnostics for spatial\n\tdependence\n\ndata:  \nmodel: lm(formula = nSpecies ~ map + tempRange, data = birdsSf)\ntest weights: WBirds\n\nRSlag = 33.448, df = 1, p-value = 7.321e-09\n\n\n\tRao's score (a.k.a Lagrange multiplier) diagnostics for spatial\n\tdependence\n\ndata:  \nmodel: lm(formula = nSpecies ~ map + tempRange, data = birdsSf)\ntest weights: WBirds\n\nadjRSerr = 107.73, df = 1, p-value < 2.2e-16\n\n\n\tRao's score (a.k.a Lagrange multiplier) diagnostics for spatial\n\tdependence\n\ndata:  \nmodel: lm(formula = nSpecies ~ map + tempRange, data = birdsSf)\ntest weights: WBirds\n\nadjRSlag = 0.37184, df = 1, p-value = 0.542\n\n\n\tRao's score (a.k.a Lagrange multiplier) diagnostics for spatial\n\tdependence\n\ndata:  \nmodel: lm(formula = nSpecies ~ map + tempRange, data = birdsSf)\ntest weights: WBirds\n\nSARMA = 141.18, df = 2, p-value < 2.2e-16\n```\n\n\n:::\n:::\n\n\nBoth RSerr and RSlag are significant. Go to the robust tests. adjRSerr is large and stays significant; adjRSlag collapses to near zero. The error model is the right fit.\n\n### Spatial Error Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsemBirds <- errorsarlm(nSpecies ~ map + tempRange,\n  data = birdsSf, listw = WBirds\n)\nsummary(semBirds)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:errorsarlm(formula = nSpecies ~ map + tempRange, data = birdsSf, \n    listw = WBirds)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-133.6497  -12.8050    0.7134   11.8756   60.3406 \n\nType: error \nCoefficients: (asymptotic standard errors) \n               Estimate  Std. Error z value  Pr(>|z|)\n(Intercept) 245.0812346  20.1854247 12.1415 < 2.2e-16\nmap           0.0727603   0.0052084 13.9699 < 2.2e-16\ntempRange    -2.7528487   0.6849927 -4.0188  5.85e-05\n\nLambda: 0.72462, LR test value: 74.723, p-value: < 2.22e-16\nAsymptotic standard error: 0.059692\n    z-value: 12.139, p-value: < 2.22e-16\nWald statistic: 147.36, p-value: < 2.22e-16\n\nLog likelihood: -909.5156 for error model\nML residual variance (sigma squared): 478.86, (sigma: 21.883)\nNumber of observations: 200 \nNumber of parameters estimated: 5 \nAIC: 1829, (AIC for lm: 1901.8)\n```\n\n\n:::\n:::\n\n\nLambda is 0.72, highly significant. There is strong spatial autocorrelation in the errors above and beyond what precipitation and temperature range explain. Check the residuals.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbirdsSf$sem_resids <- residuals(semBirds)\nmoran.test(birdsSf$sem_resids, WBirds)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMoran I test under randomisation\n\ndata:  birdsSf$sem_resids  \nweights: WBirds    \n\nMoran I statistic standard deviate = 0.43109, p-value = 0.3332\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n      0.008848150      -0.005025126       0.001035655 \n```\n\n\n:::\n:::\n\n\nMoran's I drops to near zero. The spatial structure has been absorbed into lambda. Compare AIC.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nAIC(olsBirds, semBirds)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         df      AIC\nolsBirds  4 1901.754\nsemBirds  5 1829.031\n```\n\n\n:::\n:::\n\n\nA drop of about 73 units. The error model is substantially better.\n\n### What Changed\n\nThe coefficients shift after accounting for spatial error dependence. The effect of `tempRange` gets stronger: OLS estimated -1.76 species per degree of range; the SEM estimates -2.75. OLS was underestimating the temperature effect because spatially autocorrelated errors were confounding the estimate. The precipitation coefficient shifts less, from 0.078 to 0.073, which makes sense given how dominant that predictor is.\n\nWhat does lambda = 0.72 mean ecologically? Precipitation and temperature range explain most of the richness gradient, but there's substantial residual spatial structure they don't capture. Some of it is almost certainly habitat heterogeneity: the Sierra Madre Occidental and Oriental are centers of endemism and provide topographic complexity that flat climate variables miss. Some may reflect historical biogeography -- proximity to the Neotropical source pool in southern Mexico leaves a signature that current climate alone doesn't explain. The SEM doesn't tell you what the missing variable is. It tells you that something spatially structured is out there and that ignoring it was biasing your inference.\n\n## A Note on Interpreting Lag Model Coefficients\n\nIn an OLS or SEM, $\\hat\\beta_1 = 0.5$ means: a one-unit increase in $x$ is associated with a 0.5-unit increase in $y$. That is a total effect.\n\nIn a SLM, a change in $x_i$ affects $y_i$ directly, but that change in $y_i$ then propagates to neighboring locations because their $y$ values depend on $y_i$ via the lag term. Those ripples feed back. The $\\hat\\beta_1$ from `lagsarlm` is only the direct local effect, before the spatial propagation plays out. The full marginal effect, including spillovers, requires computing impacts from the fitted model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nimpacts(slmFit, listw = W, R = 500)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nImpact measures (lag, exact):\n           Direct  Indirect    Total\nx dy/dx 0.4626068 0.6786596 1.141266\n```\n\n\n:::\n:::\n\n\nThe output decomposes effects into direct (same-location), indirect (spillover to neighbors), and total. For most environmental science applications, the total effects are what you want to report if you are using a lag model. If the indirect effects are small relative to the direct effects, the distinction matters less in practice, but check.\n\nThe lag model is making a more specific and more mechanistic claim about the data-generating process than the error model. The error model is the cleaner choice when you just want valid inference on your predictors and space is nuisance variation.\n\n## GLS vs. SAR: When to Use Which\n\nThey are often interchangeable in practice for the spatial error case.\n\nGLS uses a variogram, a continuous function of distance, to model the error correlation structure. It captures the range, sill, and nugget of the spatial dependence and is very flexible. SAR models use a discrete neighbor structure: you define who counts as a neighbor and the autocorrelation operates only among neighbors. GLS tends to work better when you have a clear distance-decay structure and a reasonable sample size to fit the variogram. SAR works better when your data are naturally defined by adjacency or neighborhood (watershed catchments, habitat patches, gridded climate data) and when you want to lean on the weights matrix you have already built for exploratory work like LISA.\n\nThe spatial lag model has no direct GLS equivalent. If the biology or ecology predicts a spillover or diffusion process, fit the lag model. Just be careful with the coefficients.\n\n## Wrapping Up\n\nGLS and SAR are both corrections to the same problem: OLS residuals that carry spatial signal the model hasn't explained. Which one you reach for depends on your data and your question. For most field-based environmental science, GLS is the workhorse. It's flexible, connects directly to the variogram, and the output is easy to interpret. SAR is worth knowing when the spatial structure is better described by a neighbor graph than a continuous distance decay, or when there's a credible spillover process in the response itself. Sometimes that mechanism is at work -- think about how disease spreads, or how animal behavior in one patch influences neighboring patches. But for lead in floodplain soil, space is probably just a proxy for flood exposure. Use GLS and sleep well.\n\n## Exercises\n\nThe Meuse River data contains several candidate predictors for soil lead contamination. `river_dist_m` is the distance from the river channel in meters and `ffreq` is a flooding frequency class (a factor with three levels: 1 = most frequent, 3 = least frequent). Both are plausible drivers of lead deposition: proximity to the channel means exposure to recent flood sediment, and flooding frequency determines how much sediment accumulates.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmeuse2 <- readRDS(\"data/meuse2.Rds\")\nmeuse.grid2 <- readRDS(\"data/meuse.grid2.Rds\")\nmeuseSf <- st_as_sf(meuse2, coords = c(\"x\", \"y\"), crs = 28992)\nmeuseSf$log_lead <- log(meuseSf$lead)\n# get river distance and flooding frequency from the grid\ncovarsSf <- st_as_sf(meuse.grid2, coords = c(\"x\", \"y\"), crs = 28992) %>%\n  select(ffreq, river_dist_m)\nmeuseSf <- st_join(meuseSf, covarsSf, join = st_nearest_feature) %>%\n  mutate(ffreq = factor(ffreq))\n```\n:::\n\n\n1. Build a k-nearest-neighbor weights matrix with $k = 8$.\n\n2. Fit OLS of `log_lead ~ river_dist_m + ffreq`. Interpret the coefficients -- do the signs make ecological sense? Run Moran's I on the residuals.\n\n3. Run the LM tests. Both RSerr and RSlag will be significant. Look at the robust tests to break the tie. Which model do they recommend?\n\n4. Fit both the SEM and the SLM. Check the residuals of each using Moran's I. One model cleans up the spatial structure; the other doesn't. Which is which, and what does that tell you?\n\n5. Compare AIC across OLS, SEM, and SLM. Does AIC agree with the LM tests?\n\n6. Compare coefficients on `river_dist_m` and `ffreq` between OLS and the SEM. The point estimates shift and the standard errors change. What does the shift in standard errors tell you about what OLS was doing wrong?\n\n7. Is the spatial error model or the spatial lag model more ecologically defensible for soil lead? What process would the lag model imply, and is that a plausible mechanism for how lead ends up in floodplain soil?\n\n8. In the bird richness example, lambda = 0.72 after accounting for precipitation and temperature range. What do you think is driving the residual spatial structure? Name at least two candidate variables not in the model and explain why they might be spatially structured across Mexico.\n\n## Further Reading\n\n@dormann2007methods sections 3.3 and 3.4 cover spatial error models and related approaches. @bivand2008geostatistics chapter 9 goes deep on the SAR model family and the `spatialreg` functions; it's a technical chapter, but worth returning to once you've worked through the examples here.\n",
    "supporting": [
      "11SpatialRegressionSAR_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}