<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Spatial analysis notes and exercises">

<title>Probabilistic Interpolation: Kriging – Spatial Analysis for Environmental Science</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./06xAsideGeostatsKrigingVariance.html" rel="next">
<link href="./05bGeostat2TPS.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-7f77c891be54f4a4e70d5699258b6bb7.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="custom.css">
</head>

<body class="nav-sidebar floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Spatial Analysis for Environmental Science</span>
    </a>
  </div>
        <div class="quarto-navbar-tools tools-end">
    <a href="https://github.com/AndyBunn/spatialNotes" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
          <div id="quarto-search" class="" title="Search"></div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./05aGeostatsIDW.html">Interpolation &amp; Geostatistics</a></li><li class="breadcrumb-item"><a href="./06aGeostatsKriging.html"><span class="chapter-title">Probabilistic Interpolation: Kriging</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Cover</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./00Welcome.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Why Spatial Analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01GettingStarted.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Introduction: Getting Your Bearings</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01xAsideMethodsAndGenerics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Aside: Understanding Methods and Generics in R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02MtBakerMap.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Mt Baker Map</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Point Patterns &amp; Autocorrelation</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03Point_Patterns.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Point Patterns</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03xAsideDistanceMatrices.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Aside: Distance Matrices</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04Intro2Autocorrelation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Spatial Autocorrelation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04xAsideCorrelationVersusRegression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Aside: Correlation is not Regression</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Interpolation &amp; Geostatistics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05aGeostatsIDW.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Deterministic Interpolation: Inverse Distance Weighting</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05xAsideModelSkill.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Aside: Model Skill and Cross Validation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05bGeostat2TPS.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Deterministic Interpolation: Thin-Plate Splines</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06aGeostatsKriging.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Probabilistic Interpolation: Kriging</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06xAsideGeostatsKrigingVariance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Aside: Kriging Variance By Hand</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06bGeostatsRegressionKriging.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Probabilistic Interpolation: Regression Kriging</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06xAsidePredictingNewData.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Aside: Predicting New Data with a Fitted Model</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Regression</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07RegressionGLS.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Regression: GLS with Autocorrelated Residuals</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07xAsideOLS-Algebra-Matrix.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Aside: OLS via Algebra and Matrices</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08PackagesUsed.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#reading" id="toc-reading" class="nav-link active" data-scroll-target="#reading">Reading</a></li>
  <li><a href="#big-idea" id="toc-big-idea" class="nav-link" data-scroll-target="#big-idea">Big Idea</a></li>
  <li><a href="#packages" id="toc-packages" class="nav-link" data-scroll-target="#packages">Packages</a></li>
  <li><a href="#some-kriging-theory" id="toc-some-kriging-theory" class="nav-link" data-scroll-target="#some-kriging-theory">Some Kriging Theory</a></li>
  <li><a href="#variogram-redux" id="toc-variogram-redux" class="nav-link" data-scroll-target="#variogram-redux">Variogram Redux</a></li>
  <li><a href="#variogram-model" id="toc-variogram-model" class="nav-link" data-scroll-target="#variogram-model">Variogram Model</a></li>
  <li><a href="#putting-it-together" id="toc-putting-it-together" class="nav-link" data-scroll-target="#putting-it-together">Putting it Together</a></li>
  <li><a href="#toy-example" id="toc-toy-example" class="nav-link" data-scroll-target="#toy-example">Toy Example</a>
  <ul>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">Data</a></li>
  <li><a href="#interpolate-with-kriging" id="toc-interpolate-with-kriging" class="nav-link" data-scroll-target="#interpolate-with-kriging">Interpolate with Kriging</a></li>
  </ul></li>
  <li><a href="#application-kriging-a-lead-surface" id="toc-application-kriging-a-lead-surface" class="nav-link" data-scroll-target="#application-kriging-a-lead-surface">Application: Kriging a Lead Surface</a></li>
  <li><a href="#uncertainty" id="toc-uncertainty" class="nav-link" data-scroll-target="#uncertainty">Uncertainty</a></li>
  <li><a href="#other-variogram-models" id="toc-other-variogram-models" class="nav-link" data-scroll-target="#other-variogram-models">Other Variogram Models</a></li>
  <li><a href="#other-types-of-kriging" id="toc-other-types-of-kriging" class="nav-link" data-scroll-target="#other-types-of-kriging">Other Types of Kriging</a></li>
  <li><a href="#cross-validation" id="toc-cross-validation" class="nav-link" data-scroll-target="#cross-validation">Cross Validation</a></li>
  <li><a href="#the-payoff" id="toc-the-payoff" class="nav-link" data-scroll-target="#the-payoff">The Payoff</a></li>
  <li><a href="#your-work" id="toc-your-work" class="nav-link" data-scroll-target="#your-work">Your Work</a></li>
  <li><a href="#postscript-automap" id="toc-postscript-automap" class="nav-link" data-scroll-target="#postscript-automap">Postscript: Automap</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/AndyBunn/spatialNotes/edit/main/06aGeostatsKriging.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/AndyBunn/spatialNotes/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./05aGeostatsIDW.html">Interpolation &amp; Geostatistics</a></li><li class="breadcrumb-item"><a href="./06aGeostatsKriging.html"><span class="chapter-title">Probabilistic Interpolation: Kriging</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Probabilistic Interpolation: Kriging</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="reading" class="level2">
<h2 class="anchored" data-anchor-id="reading">Reading</h2>
<p>We will finish Ch 8 in Bivand <span class="citation" data-cites="bivand2008geostatistics">(<a href="08PackagesUsed.html#ref-bivand2008geostatistics" role="doc-biblioref">Bivand 2008</a>)</span>. Sections 8.4 and 8.5 are the most important for this module. It’s fairly dense after that. Review <span class="citation" data-cites="fortin2016spatial">Fortin et al. (<a href="08PackagesUsed.html#ref-fortin2016spatial" role="doc-biblioref">2016</a>)</span> as well, especially 4.3 to 4.5</p>
</section>
<section id="big-idea" class="level2">
<h2 class="anchored" data-anchor-id="big-idea">Big Idea</h2>
<p>We often want to estimate phenomena at locations where we do not have measurements. Geostatistics is the field that we use to make (hopefully) accurate and reliable models of spatial data. We will use these models for prediction. We can use both deterministic and probabilistic models and this module will focus on probabilistic methods. Kriging is a probabilistic method that finds spatial pattern and predicts unknown values based on that spatial pattern. Unlike IDW, kriging generates a measure of uncertainty allowing us to estimate confidence in the predictions.</p>
</section>
<section id="packages" class="level2">
<h2 class="anchored" data-anchor-id="packages">Packages</h2>
<p>The <code>gstat</code><span class="citation" data-cites="R-gstat">(<a href="08PackagesUsed.html#ref-R-gstat" role="doc-biblioref">Pebesma and Graeler 2026</a>)</span> package is your friend. And I’m going to plot in <code>ggplot</code> via <code>tidyverse</code><span class="citation" data-cites="R-tidyverse">(<a href="08PackagesUsed.html#ref-R-tidyverse" role="doc-biblioref">Wickham 2023</a>)</span> with <code>sf</code><span class="citation" data-cites="R-sf">(<a href="08PackagesUsed.html#ref-R-sf" role="doc-biblioref">Pebesma 2026</a>)</span>, <code>terra</code><span class="citation" data-cites="R-terra">(<a href="08PackagesUsed.html#ref-R-terra" role="doc-biblioref">Hijmans 2026</a>)</span> and <code>tidyterra</code><span class="citation" data-cites="R-tidyterra">(<a href="08PackagesUsed.html#ref-R-tidyterra" role="doc-biblioref">Hernangómez 2023</a>)</span>. We’ll also use <code>automap</code><span class="citation" data-cites="R-automap">(<a href="08PackagesUsed.html#ref-R-automap" role="doc-biblioref">Hiemstra et al. 2008</a>)</span> for automatic variogram fitting.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gstat)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(terra)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyterra)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(automap)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="some-kriging-theory" class="level2">
<h2 class="anchored" data-anchor-id="some-kriging-theory">Some Kriging Theory</h2>
<p>IDW is a deterministic interpolation method. That is, it relies on a specified mathematical formula that is not a function of the statistical relationship among the known points. This method has no error term associated with it and in fact isn’t really geostatistical in a strict sense. Now, you might like to have no error in your estimation, but just because IDW doesn’t spit out an error term doesn’t mean that no error exists. A true geostatistical technique not only produces a prediction surface but also provides some measure of the accuracy of the predictions. Recall how the names in the IDW objects we calculated had a blank column (<code>var1.var</code>)? That’s where the error surface will be in addition to the predictions (<code>var1.pred</code>) as we move forward with a probabilistic approach to interpolation called Kriging.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The method is named after Danie Krige, a South African mining engineer who developed distance-weighted averaging to estimate gold grade distributions from borehole samples at the Witwatersrand reef complex in the 1950s.The Witwatersrand Basin is the world’s largest known gold repository. The French mathematician Georges Matheron later formalized the theoretical framework in 1960. So yes, kriging started as a way to find gold. The verb is “to krige” and you will see it both capitalized and not in the literature – both are fine.</p>
</div>
</div>
<p>Kriging is a geostatistical method of interpolation that uses spatial autocorrelation, and it works best when there is strong autocorrelation in the data. When kriging we use the distance between sample points (and sometimes direction) to explain variation in a variable. We then fit a mathematical model to a specified number of points (or points within a certain distance) to determine the output value for each location.</p>
<p>The approach will make heavy use of the variograms that we started with earlier in the class. They are how we are going to determine the parameter <span class="math inline">\(\lambda\)</span> in the formula for kriging:</p>
<p><span class="math display">\[\hat{Z}(s_0)=\sum_{i=1}^n \lambda_i Z(s_i)\]</span></p>
<p>where <span class="math inline">\(\hat{Z}\)</span> will be an estimate of a variable at a spatial location <span class="math inline">\(s_0\)</span> where we haven’t measured <span class="math inline">\(Z\)</span> and <span class="math inline">\(s_i\)</span> a location, <span class="math inline">\(i\)</span>, where we have measured <span class="math inline">\(Z\)</span>. There are <span class="math inline">\(n\)</span> measurements. Analogous to the <span class="math inline">\(w\)</span> terms for IDW, <span class="math inline">\(\lambda_i\)</span> is a weight for the measured value at location <span class="math inline">\(s_i\)</span>. With IDW the weight was a deterministic function of distance. With kriging, we use the distance between the measured points and the prediction location as well as the overall spatial structure of the measured points themselves. That spatial structure is the spatial autocorrelation measured by the variogram. Let’s review variograms.</p>
</section>
<section id="variogram-redux" class="level2">
<h2 class="anchored" data-anchor-id="variogram-redux">Variogram Redux</h2>
<p>Fitting a variogram is also called structural analysis and it is where we calculate the squared difference between the values of pairs of measured points. In the variogram we set this as <span class="math inline">\(\gamma = (z_i-z_j)^2/2\)</span>. We then plot <span class="math inline">\(\gamma\)</span> against distance and we have a variogram cloud. In practice the number of pairs (dyads) to calculate and plot gets very large. For <span class="math inline">\(n\)</span> points there are <span class="math inline">\(n \cdot (n-1) / 2\)</span> pairs. So, instead of plotting each pair we average <span class="math inline">\(\gamma\)</span> by distance bins. This is the empirical semivariogram.</p>
<p>We will demonstrate a variogram with the <code>meuse</code> data. Here we load the meuse point data and the gridded data as <code>data.frame</code>, make a new variable by logging the <code>lead</code> column and plot them. This is the same procedure we used when doing IDW.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(meuse.all)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>meuse.grid <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">"data/meuse.grid.Rds"</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="co"># make a variable to work with</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>meuse.all<span class="sc">$</span>logLead <span class="ot">&lt;-</span> <span class="fu">log</span>(meuse.all<span class="sc">$</span>lead)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co"># make into sf</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>meuse_sf <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(meuse.all, <span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"x"</span>, <span class="st">"y"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_set_crs</span>(<span class="at">value =</span> <span class="dv">28992</span>)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>meuse_grid_sf <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(meuse.grid, </span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>                          <span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"x"</span>,<span class="st">"y"</span>), </span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>                          <span class="at">crs =</span> <span class="fu">st_crs</span>(meuse_sf))</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>meuse_grid_sf</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 3103 features and 5 fields
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: 178460 ymin: 329620 xmax: 181540 ymax: 333740
Projected CRS: Amersfoort / RD New
First 10 features:
   part.a part.b       dist soil ffreq              geometry
1       1      0 0.00000000    1     1 POINT (181180 333740)
2       1      0 0.00000000    1     1 POINT (181140 333700)
3       1      0 0.01222430    1     1 POINT (181180 333700)
4       1      0 0.04346780    1     1 POINT (181220 333700)
5       1      0 0.00000000    1     1 POINT (181100 333660)
6       1      0 0.01222430    1     1 POINT (181140 333660)
7       1      0 0.03733950    1     1 POINT (181180 333660)
8       1      0 0.05936620    1     1 POINT (181220 333660)
9       1      0 0.00135803    1     1 POINT (181060 333620)
10      1      0 0.01222430    1     1 POINT (181100 333620)</code></pre>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> meuse_sf) <span class="sc">+</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="fu">aes</span>(<span class="at">fill=</span>logLead), <span class="at">size=</span><span class="dv">4</span>, </span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">shape =</span> <span class="dv">21</span>, <span class="at">color=</span><span class="st">"white"</span>,<span class="at">alpha=</span><span class="fl">0.8</span>)<span class="sc">+</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_continuous</span>(<span class="at">type =</span> <span class="st">"viridis"</span>,<span class="at">name=</span><span class="st">"log(ppm)"</span>) <span class="sc">+</span> </span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Lead concentrations"</span>)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>p1</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="06aGeostatsKriging_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We will use the <code>variogram</code> function in <code>gstat</code>. Look back at the autocorrelation module for review as needed.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>leadVar <span class="ot">&lt;-</span> <span class="fu">variogram</span>(logLead<span class="sc">~</span><span class="dv">1</span>, meuse_sf)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(leadVar,<span class="at">pch=</span><span class="dv">20</span>,<span class="at">cex=</span><span class="fl">1.5</span>,<span class="at">col=</span><span class="st">"black"</span>,</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab=</span><span class="fu">expression</span>(<span class="st">"Semivariance ("</span><span class="sc">*</span>gamma<span class="sc">*</span><span class="st">")"</span>),</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">"Distance (m)"</span>, <span class="at">main =</span> <span class="st">"Lead concentrations (log(ppm))"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="06aGeostatsKriging_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This is the sample, or empirical, semivariogram. We interpret it as measurements that are closer together (left on the x-axis) have similar values (low values of <span class="math inline">\(\gamma\)</span>). As we move to pairs further apart (right on the x-axis) the semivariogram increases; values are more dissimilar and thus have a higher value of <span class="math inline">\(\gamma\)</span>. Our next job is going to be to fit a model to the points on the variogram. Before we do that, let’s appreciate the three terms for describing the variogram.</p>
<p><img src="assets/Variogram.gif" class="img-fluid"></p>
<ul>
<li>The <strong>range</strong> is the distance beyond which the data are no longer correlated.</li>
<li>The <strong>sill</strong> is the variance of the variable.</li>
<li>The <strong>nugget</strong> is the autocorrelation at very small scales. The nugget represents independent error, measurement error and/or micro-scale variation at fine spatial scales. In a continuous variable we would expect that the nugget effect will be zero because at distance zero the values will be the same. However some variables can change in an abrupt manner and so in very short distance there is a difference.</li>
</ul>
<p>If there is no structure (no correlation) and the variable is therefore a purely random variable, the variogram will be flat with a nugget effect.</p>
</section>
<section id="variogram-model" class="level2">
<h2 class="anchored" data-anchor-id="variogram-model">Variogram Model</h2>
<p>After plotting the <strong>sample</strong> variogram we can then fit a statistical <strong>model</strong> to the points. The model is a continuous estimate of <span class="math inline">\(\gamma\)</span> as a function of distance: <span class="math inline">\(\hat{\gamma}=f(d)\)</span>.</p>
<p>We will fit two different functions, a spherical model and an exponential model. The text has descriptions of the various functions. In practice, we tend to look at the general shape of the plot and then choose a mathematical model that fits.</p>
<p>Note that <code>gstat</code> uses the partial sill (<code>psill</code>) which is the sill minus the nugget. Just to be confusing. Thanks <code>gstat</code>.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># note our initial estimates for the partial sill, range, and nugget. </span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>sph.model <span class="ot">&lt;-</span> <span class="fu">vgm</span>(<span class="at">psill=</span><span class="fl">0.5</span>, <span class="at">model=</span><span class="st">"Sph"</span>, <span class="at">range=</span><span class="dv">750</span>, <span class="at">nugget=</span><span class="fl">0.05</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>sph.fit <span class="ot">&lt;-</span> <span class="fu">fit.variogram</span>(<span class="at">object =</span> leadVar, <span class="at">model =</span> sph.model)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>sph.fit <span class="co"># look at the fitted values</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  model     psill    range
1   Nug 0.1095742    0.000
2   Sph 0.4560318 1002.626</code></pre>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(leadVar,<span class="at">model=</span>sph.fit,<span class="at">pch=</span><span class="dv">20</span>,<span class="at">cex=</span><span class="fl">1.5</span>,<span class="at">col=</span><span class="st">"black"</span>,</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab=</span><span class="fu">expression</span>(<span class="st">"Semivariance ("</span><span class="sc">*</span>gamma<span class="sc">*</span><span class="st">")"</span>),</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">"Distance (m)"</span>, <span class="at">main =</span> <span class="st">"Lead concentrations (log(ppm))"</span>,</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">sub=</span><span class="st">"Points: Empirical, Line: Spherical Model"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="06aGeostatsKriging_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We now have a fitted, theoretical, variogram model to the data in the <code>sph.fit</code> object. This object took our estimates of the partial sill, range, and nugget and found the best fits from those estimates using non-linear regression. The final parameters are pretty close to our estimates from the plot. E.g., the fitted nugget is 0.11 and the range is 1002.63. If we gave initial estimates way outside the realm of possibility the function wouldn’t be able to fit the model. But if the data are well behaved it converges on the best fit pretty easily. If you are too scared to estimate initial values in <code>vgm</code> the function will estimate them for you. See Details under <code>?fit.variogram</code> for how those are calculated. E.g., in this application if you try <code>sph.model &lt;- vgm(model="Sph",nugget=TRUE)</code> the <code>fit.variogram</code> algorithm converges without initial estimates.</p>
<p>The actual function for the spherical model is:</p>
<p><span class="math display">\[\hat{\gamma}(d)= b + C_0 \left(1.5\left(\frac{d}{r}\right) - 0.5 \left(\frac{d^3}{r^3}\right)\right)\]</span></p>
<p>where <span class="math inline">\(b\)</span> is the nugget, <span class="math inline">\(C_0\)</span> is the partial sill, <span class="math inline">\(d\)</span> is the distance, and <span class="math inline">\(r\)</span> is the range. Note the <span class="math inline">\(r^3\)</span> in the denominator of the second term, not <span class="math inline">\(r\)</span>. The cubic term is what gives the spherical model its characteristic shape: it rises steeply at short distances and flattens out as it approaches the sill at distance <span class="math inline">\(r\)</span>, after which <span class="math inline">\(\hat{\gamma}\)</span> is constant.</p>
<p>The spherical model above is very commonly used and has nice theoretical properties, using all three classic parameters of the variogram. We could, if we liked, fit some other models – an exponential model would fit well here too.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># note our initial estimates for the sill, range, and nugget</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>exp.model <span class="ot">&lt;-</span> <span class="fu">vgm</span>(<span class="at">psill=</span><span class="fl">0.5</span>, <span class="at">model=</span><span class="st">"Exp"</span>, <span class="at">range=</span><span class="dv">750</span>, <span class="at">nugget=</span><span class="fl">0.05</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>exp.fit <span class="ot">&lt;-</span> <span class="fu">fit.variogram</span>(<span class="at">object =</span> leadVar, <span class="at">model =</span> exp.model)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(leadVar,<span class="at">model=</span>exp.fit,<span class="at">pch=</span><span class="dv">20</span>,<span class="at">cex=</span><span class="fl">1.5</span>,<span class="at">col=</span><span class="st">"black"</span>,</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab=</span><span class="fu">expression</span>(<span class="st">"Semivariance ("</span><span class="sc">*</span>gamma<span class="sc">*</span><span class="st">")"</span>),</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">"Distance (m)"</span>, <span class="at">main =</span> <span class="st">"Lead concentrations (log(ppm))"</span>,</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">sub=</span><span class="st">"Points: Empirical, Line: Exponential Model"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="06aGeostatsKriging_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This model is <span class="math inline">\(\hat{\gamma}(d)=b + C_0(1-e^{-d/a})\)</span> where <span class="math inline">\(a=r/3\)</span> and other terms are as above. Unlike the spherical model, the exponential never quite reaches the sill – it approaches asymptotically. For many data sets both models fit about equally well, and choosing between them comes down to visual inspection and, ultimately, cross-validation skill.</p>
</section>
<section id="putting-it-together" class="level2">
<h2 class="anchored" data-anchor-id="putting-it-together">Putting it Together</h2>
<p>We have a fitted variogram model now. That is <span class="math inline">\(\hat{\gamma}(d)\)</span>, an estimate of spatial structure at any distance. Here is our kriging formula again:</p>
<p><span class="math display">\[\hat{Z}(s_0)=\sum_{i=1}^n \lambda_i Z(s_i)\]</span></p>
<p>How do we get to the weights (<span class="math inline">\(\lambda\)</span>)? From the variogram model. The guts of this calculation involve a little matrix algebra to fully work through, but conceptually it is pretty simple: <span class="math display">\[ \lambda = \Gamma^{-1} g \]</span></p>
<p>where <span class="math inline">\(\Gamma\)</span> is a matrix of the semivariances for all sampled point pairs, predicted as a function of their Euclidean distances using the fitted variogram model, and <span class="math inline">\(g\)</span> is a vector of predicted semivariances between the unknown point and each measured point, calculated the same way. Once we have <span class="math inline">\(\lambda\)</span> we can interpolate (predict) over a surface for any location where we don’t have <span class="math inline">\(Z\)</span>.</p>
</section>
<section id="toy-example" class="level2">
<h2 class="anchored" data-anchor-id="toy-example">Toy Example</h2>
<p>Like we did with IDW, let’s walk through this calculation with a contrived example.</p>
<section id="data" class="level3">
<h3 class="anchored" data-anchor-id="data">Data</h3>
<p>Here is a small data set of five points. We have spatial coordinates (<span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>) and some measured variable (<span class="math inline">\(z\)</span>).</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>foo <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>,<span class="dv">1</span>,<span class="dv">4</span>,<span class="dv">5</span>),</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">y =</span> <span class="fu">c</span>(<span class="dv">5</span>,<span class="dv">4</span>,<span class="dv">3</span>,<span class="dv">5</span>,<span class="dv">1</span>),</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">z =</span> <span class="fu">c</span>(<span class="dv">100</span>,<span class="dv">105</span>,<span class="dv">105</span>,<span class="dv">100</span>,<span class="dv">115</span>))</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>foo</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  x y   z
1 1 5 100
2 3 4 105
3 1 3 105
4 4 5 100
5 5 1 115</code></pre>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data=</span>foo,<span class="fu">aes</span>(<span class="at">x=</span>x,<span class="at">y=</span>y,<span class="at">size=</span>z)) <span class="sc">+</span> </span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lims</span>(<span class="at">x=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">6</span>),<span class="at">y=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">6</span>))</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>p2</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="06aGeostatsKriging_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Let’s imagine a point <span class="math inline">\(x=2\)</span> and <span class="math inline">\(y=4\)</span> where we don’t know <span class="math inline">\(z\)</span>.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> p2 <span class="sc">+</span> </span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x=</span><span class="dv">2</span>,<span class="at">y=</span><span class="dv">4</span>),<span class="at">color=</span><span class="st">"red"</span>,<span class="at">size=</span><span class="dv">10</span>,<span class="at">shape=</span><span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x=</span><span class="dv">2</span>,<span class="at">y=</span><span class="dv">4</span>),<span class="at">color=</span><span class="st">"red"</span>,<span class="at">size=</span><span class="dv">6</span>,<span class="at">shape=</span><span class="dv">63</span>)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>p2</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="06aGeostatsKriging_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="interpolate-with-kriging" class="level3">
<h3 class="anchored" data-anchor-id="interpolate-with-kriging">Interpolate with Kriging</h3>
<p>We are now going to use kriging as a way to get an estimate of that point with a missing value of <span class="math inline">\(z\)</span>. Since we are estimating it we call it <span class="math inline">\(\hat{Z}\)</span> and we know the location as <span class="math inline">\(s_0\)</span> so we call this <span class="math inline">\(\hat{Z}(s_0)\)</span>. We’ll follow the notation above.</p>
<p>The Euclidean distance to our unknown point from each of the known points is a vector:</p>
<p><span class="math display">\[\mathbf{d_i} = \left[\begin{array}
{rr}
1 &amp; 1.414\\
2 &amp; 1.000\\
3 &amp; 1.414\\
4 &amp; 2.236\\
5 &amp; 4.243
\end{array}\right]\]</span></p>
<p>To get <span class="math inline">\(\hat{Z}(s_0)\)</span> we apply <span class="math inline">\(\lambda = \Gamma^{-1} g\)</span> from above. Now, these five data points don’t actually make a nice variogram. So let’s suspend disbelief for a moment and say we fit a spherical model with nugget <span class="math inline">\(= 0\)</span>, partial sill <span class="math inline">\(= 10\)</span>, and range <span class="math inline">\(= 6\)</span>. Those aren’t fitted values from this tiny dataset, just reasonable numbers for a worked example.</p>
<p><span class="math display">\[\hat{\gamma}(d) = 10\left(1.5\left(\frac{d}{6}\right) - 0.5\left(\frac{d}{6}\right)^3\right) \quad \text{for } d \leq 6\]</span></p>
<p>First we can calculate <span class="math inline">\(g\)</span> for the point we want to interpolate by plugging each distance <span class="math inline">\(d_i\)</span> into the variogram model:</p>
<p><span class="math display">\[\mathbf{g} = \left[\begin{array}
{rr}
1 &amp; 3.470\\
2 &amp; 2.477\\
3 &amp; 3.470\\
4 &amp; 5.331\\
5 &amp; 8.839
\end{array}\right]\]</span></p>
<p>Now, let’s get <span class="math inline">\(\Gamma\)</span>. First, here is the distance matrix between all the measured points:</p>
<p><span class="math display">\[\mathbf{d} = \left[\begin{array}
{rrrrr}
~ &amp; 1 &amp; 2 &amp; 3 &amp; 4 \\
2 &amp; 2.236 &amp; ~ &amp; ~ &amp; ~ \\
3 &amp; 2.000 &amp; 2.236 &amp; ~ &amp; ~ \\
4 &amp; 3.000 &amp; 1.414 &amp; 3.606 &amp; ~ \\
5 &amp; 5.657 &amp; 3.606 &amp; 4.472 &amp; 4.123
\end{array}\right]\]</span></p>
<p>We apply the same spherical variogram model to the distances between all measured points to get <span class="math inline">\(\Gamma\)</span>:</p>
<p><span class="math display">\[\mathbf{\Gamma} = \left[\begin{array}
{rrrrr}
~ &amp; 1 &amp; 2 &amp; 3 &amp; 4 \\
2 &amp; 5.331 &amp; ~ &amp; ~ &amp; ~ \\
3 &amp; 4.815 &amp; 5.331 &amp; ~ &amp; ~ \\
4 &amp; 6.875 &amp; 3.470 &amp; 7.929 &amp; ~ \\
5 &amp; 9.952 &amp; 7.929 &amp; 9.110 &amp; 8.685
\end{array}\right]\]</span></p>
<p>We now need the inverse of <span class="math inline">\(\Gamma\)</span>. Inverting a matrix bigger than say 2x2 is not something I want to do by hand. Inverting a 5x5 matrix by hand would take me all day and I’d definitely screw it up. If you can’t recall how to invert a matrix you can check out the always helpful Kahn Academy’s take on it <a href="https://www.khanacademy.org/math/precalculus/precalc-matrices/intro-to-matrix-inverses/v/inverse-matrix-part-1">here</a>. In R you can use the <code>solve</code> function (or <code>ginv</code> in the <code>MASS</code> package) to invert a matrix.</p>
<p><span class="math display">\[\mathbf{\Gamma^{-1}} = \left[\begin{array}
{rrrrr}
~ &amp; 1      &amp; 2      &amp; 3      &amp; 4      &amp; 5     \\
1 &amp; -0.1322 &amp; 0.0322  &amp; 0.0805  &amp; 0.0376  &amp; 0.0183  \\
2 &amp; 0.0322  &amp; -0.2308 &amp; 0.0547  &amp; 0.1164  &amp; 0.0167  \\
3 &amp; 0.0805  &amp; 0.0547  &amp; -0.1340 &amp; -0.0017 &amp; 0.0367  \\
4 &amp; 0.0376  &amp; 0.1164  &amp; -0.0017 &amp; -0.1475 &amp; 0.0404  \\
5 &amp; 0.0183  &amp; 0.0167  &amp; 0.0367  &amp; 0.0404  &amp; -0.0546
\end{array}\right]\]</span></p>
<p>And <span class="math inline">\(\lambda = \Gamma^{-1} g\)</span>: <span class="math display">\[\mathbf{\lambda_i} = \left[\begin{array}
{rr}
1 &amp; 0.2626\\
2 &amp; 0.4985\\
3 &amp; 0.2652\\
4 &amp; -0.0165\\
5 &amp; -0.0353
\end{array}\right]\]</span></p>
<p>You’ll notice that points 4 and 5 have negative weights. With IDW, every point gets a positive weight that simply shrinks with distance. Kriging is more sophisticated: it considers the spatial structure among all the measured points at once. Points 4 and 5 are far from the prediction location, so their semivariances in <span class="math inline">\(g\)</span> are large and their influence on the prediction is already small. But they’re also located in a part of the space that the closer points (1, 2, and 3) already “cover” informationally. The kriging system figures out that including points 4 and 5 with even a small positive weight would introduce a slight bias, so it assigns them tiny negative weights to correct for that. This is sometimes called a screening effect. The weights are small and don’t change the estimate much, and it isn’t a sign that something went wrong.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 100.739</code></pre>
</div>
</div>
<p>Giving the final prediction: <span class="math display">\[\hat{Z}(s_0)=0.2626(100)+0.4985(105)+0.2652(105)-0.0165(100)-0.0353(115) \approx 100.74\]</span></p>
<p>The matrix notation can be sort of tedious but hopefully you’ve gotten the idea: because of the theoretical variogram model we can estimate <span class="math inline">\(\hat{\gamma}\)</span> for any distance <span class="math inline">\(d\)</span> and use that information, along with the distance matrix among the known points, to predict <span class="math inline">\(Z\)</span> at any location.</p>
</section>
</section>
<section id="application-kriging-a-lead-surface" class="level2">
<h2 class="anchored" data-anchor-id="application-kriging-a-lead-surface">Application: Kriging a Lead Surface</h2>
<p>This will look a lot like what we did with IDW but we will use <code>krige</code> instead. And <code>krige</code> wants a fitted variogram model to be passed in. So, using the variogram from above we can do this.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>leadVar <span class="ot">&lt;-</span> <span class="fu">variogram</span>(logLead<span class="sc">~</span><span class="dv">1</span>, meuse_sf)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="co"># with initial gueses at the parameters psill, range, and nugget</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>leadModel <span class="ot">&lt;-</span> <span class="fu">vgm</span>(<span class="at">psill=</span><span class="fl">0.6</span>, <span class="at">model=</span><span class="st">"Sph"</span>, <span class="at">range=</span><span class="dv">750</span>, <span class="at">nugget=</span><span class="fl">0.05</span>)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="co"># or try to let the estimation happen without initial guesses -- same result</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>leadModel <span class="ot">&lt;-</span> <span class="fu">vgm</span>(<span class="at">model=</span><span class="st">"Sph"</span>, <span class="at">nugget=</span><span class="cn">TRUE</span>)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>leadFit <span class="ot">&lt;-</span> <span class="fu">fit.variogram</span>(<span class="at">object =</span> leadVar, <span class="at">model =</span> leadModel)</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>leadGstat <span class="ot">&lt;-</span> <span class="fu">gstat</span>(<span class="at">formula =</span> logLead<span class="sc">~</span><span class="dv">1</span>, <span class="at">locations =</span> meuse_sf, </span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>                   <span class="at">model =</span> leadFit)</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>leadKrige_sf <span class="ot">&lt;-</span> <span class="fu">predict</span>(leadGstat,<span class="at">newdata =</span> meuse_grid_sf)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[using ordinary kriging]</code></pre>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>leadKrige_sf</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 3103 features and 2 fields
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: 178460 ymin: 329620 xmax: 181540 ymax: 333740
Projected CRS: Amersfoort / RD New
First 10 features:
   var1.pred  var1.var              geometry
1   5.336713 0.3183947 POINT (181180 333740)
2   5.406841 0.2724001 POINT (181140 333700)
3   5.343480 0.2854597 POINT (181180 333700)
4   5.279198 0.3003649 POINT (181220 333700)
5   5.486278 0.2238744 POINT (181100 333660)
6   5.415401 0.2377063 POINT (181140 333660)
7   5.339935 0.2536512 POINT (181180 333660)
8   5.266665 0.2701756 POINT (181220 333660)
9   5.562294 0.1801611 POINT (181060 333620)
10  5.496279 0.1894106 POINT (181100 333620)</code></pre>
</div>
</div>
<p>Note that <code>leadKrige</code> is a <code>sf</code> object that has the predicted surface <code>var1.pred</code> but there is another surface in there too, <code>var1.var</code>, which contains the variance around those predictions. Let’s take a look at the predictions first and then spend some time with the variance surface.</p>
<p>Here is the prediction surface. Note how we specify what <code>attribute</code> we want to plot via <code>leadKrige["var1.pred"]</code>.</p>
<p>I’ll use the little function from the IDW notes to get a <code>rast</code> object from the <code>sf</code> object.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>sf_2_rast <span class="ot">&lt;-</span><span class="cf">function</span>(sfObject,<span class="at">variableIndex =</span> <span class="dv">1</span>){</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># coerce sf to a data.frame</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  dfObject <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="fu">st_coordinates</span>(sfObject),</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>                         <span class="at">z=</span><span class="fu">as.data.frame</span>(sfObject)[,variableIndex])</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># coerce data.frame to SpatRaster</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>  rastObject <span class="ot">&lt;-</span> <span class="fu">rast</span>(dfObject,<span class="at">crs=</span><span class="fu">crs</span>(sfObject))</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">names</span>(rastObject) <span class="ot">&lt;-</span> <span class="fu">names</span>(sfObject)[variableIndex]</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(rastObject)</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>leadKrige_rast <span class="ot">&lt;-</span> <span class="fu">sf_2_rast</span>(leadKrige_sf)</span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>leadKrige_rast</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>class       : SpatRaster 
size        : 104, 78, 1  (nrow, ncol, nlyr)
resolution  : 40, 40  (x, y)
extent      : 178440, 181560, 329600, 333760  (xmin, xmax, ymin, ymax)
coord. ref. : Amersfoort / RD New (EPSG:28992) 
source(s)   : memory
name        : var1.pred 
min value   :  3.749342 
max value   :  6.174216 </code></pre>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># and plot</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_spatraster</span>(<span class="at">data=</span>leadKrige_rast, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">fill=</span>var1.pred),<span class="at">alpha=</span><span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_continuous</span>(<span class="at">type =</span> <span class="st">"viridis"</span>,<span class="at">name=</span><span class="st">"log(ppm)"</span>,<span class="at">na.value =</span> <span class="st">"transparent"</span>) <span class="sc">+</span> </span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Lead concentrations"</span>) <span class="sc">+</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="06aGeostatsKriging_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Now let’s look at the variance around those predictions. Note we take the square root of <code>var1.var</code> to get the uncertainty in the same units as <code>var1.pred</code>.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>leadKrige_sf<span class="sc">$</span>var1.var.sqrt <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(leadKrige_sf<span class="sc">$</span>var1.var)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>leadKrige_rast <span class="ot">&lt;-</span> <span class="fu">sf_2_rast</span>(leadKrige_sf,<span class="at">variableIndex =</span> <span class="dv">4</span>)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>leadKrige_rast</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>class       : SpatRaster 
size        : 104, 78, 1  (nrow, ncol, nlyr)
resolution  : 40, 40  (x, y)
extent      : 178440, 181560, 329600, 333760  (xmin, xmax, ymin, ymax)
coord. ref. : Amersfoort / RD New (EPSG:28992) 
source(s)   : memory
name        : var1.var.sqrt 
min value   :     0.3881239 
max value   :     0.6503917 </code></pre>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># and plot</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_spatraster</span>(<span class="at">data=</span>leadKrige_rast, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">fill=</span>var1.var.sqrt ),<span class="at">alpha=</span><span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_continuous</span>(<span class="at">type =</span> <span class="st">"viridis"</span>,<span class="at">name=</span><span class="st">"log(ppm)"</span>,<span class="at">na.value =</span> <span class="st">"transparent"</span>) <span class="sc">+</span> </span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Variance of lead concentrations"</span>) <span class="sc">+</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="06aGeostatsKriging_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Look at the spatial pattern in that variance surface. Uncertainty is lowest near the measured points and highest at the edges of the study area where observations are sparse or absent. Compare this to the locations of your sample points in <code>meuse_sf</code> and you should see the correspondence pretty clearly. This is one of the most useful things kriging gives you: not just a prediction surface, but a map of where you should trust that surface and where you should be skeptical. IDW (and TPS) will happily interpolate across a data gap without telling you it’s doing so. The variance in Kriging helps flags weak areas of the surface.</p>
</section>
<section id="uncertainty" class="level2">
<h2 class="anchored" data-anchor-id="uncertainty">Uncertainty</h2>
<p>The variance surface is more than just a map of sample density, though sample density is a big driver of it. The variogram models we’ve been fitting (spherical, exponential, and others) are more than pretty lines we use to get a continuous estimate of <span class="math inline">\(\hat{\gamma}\)</span> as a function of distance. They have some of the same <a href="https://en.wikipedia.org/wiki/Variogram#Properties">properties</a> as statistical distributions do in probability theory. In particular, variograms are empirical estimates of the covariance of Gaussian processes. Because the model variogram gives the mean squared difference between values based on their location, we can use it to derive the uncertainty around each prediction. The variance at any prediction location is a function of how well that location is “covered” by the surrounding observations, weighted by the fitted spatial covariance structure.</p>
<p>What this means practically is that kriging variance increases when (a) the prediction location is far from any measured points, (b) the measured points nearby are themselves clustered rather than well-spread, and (c) the sill of the variogram is large, meaning the variable is highly variable across the study area. At very large distances from all data, the variance approaches the sill – which is your best estimate of how variable the field is when you have no local information at all.</p>
<p>The underlying theory goes deeper than we will cover here. Diggle’s <a href="https://books.google.com/books/about/Model_based_Geostatistics.html?id=qCqOm39OuFUC">“Model-based Geostatistics”</a> will drag you through it if you want. Bivand’s chapter has more on this too. I walk through it in the <a href="06xAsideGeostatsKrigingVariance.html">Kriging Variance By Hand aside</a>.</p>
</section>
<section id="other-variogram-models" class="level2">
<h2 class="anchored" data-anchor-id="other-variogram-models">Other Variogram Models</h2>
<p>Above I showed you the spherical and the exponential variogram models. Those are commonly used, as are the Gaussian and the Mattern models. But there are many other options – a whole slew, actually, most of which I’ve never used. Look at this:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vgm</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   short                                      long
1    Nug                              Nug (nugget)
2    Exp                         Exp (exponential)
3    Sph                           Sph (spherical)
4    Gau                            Gau (gaussian)
5    Exc        Exclass (Exponential class/stable)
6    Mat                              Mat (Matern)
7    Ste Mat (Matern, M. Stein's parameterization)
8    Cir                            Cir (circular)
9    Lin                              Lin (linear)
10   Bes                              Bes (bessel)
11   Pen                      Pen (pentaspherical)
12   Per                            Per (periodic)
13   Wav                                Wav (wave)
14   Hol                                Hol (hole)
15   Log                         Log (logarithmic)
16   Pow                               Pow (power)
17   Spl                              Spl (spline)
18   Leg                            Leg (Legendre)
19   Err                   Err (Measurement error)
20   Int                           Int (Intercept)</code></pre>
</div>
</div>
<p><code>gstat</code> knows 20 different possible curves you can fit to your data. E.g.,</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">show.vgms</span>(<span class="at">models =</span> <span class="fu">c</span>(<span class="st">"Exp"</span>, <span class="st">"Mat"</span>, <span class="st">"Gau"</span>, <span class="st">"Sph"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="06aGeostatsKriging_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The four models plotted above give you a sense of why the choice matters. The spherical model reaches the sill at a finite distance and stays there, which is appropriate when you believe the variable has a well-defined correlation length. The exponential model approaches the sill asymptotically, implying some small correlation at any distance, which suits variables that never fully decorrelate. The Gaussian model has an S-shaped approach to the sill and goes to zero slope at the origin, which implies a very smooth, continuous underlying process. The Mattern family includes both of those as special cases and is more flexible, at the cost of one extra parameter.</p>
<p>In practice, a few things constrain which models are valid at all. The variogram must be non-negative everywhere, and it must produce a covariance matrix that is positive semi-definite (that is matrix-speak for “the variances this system produces can never come out negative.”). That second condition is what makes the kriging system solvable and ensures the predicted variances come out non-negative. This is why you can’t just draw any curve through the empirical variogram and call it a model. The parametric families in <code>gstat</code> all satisfy these conditions by construction, which is a good reason to stick with them rather than trying to invent your own.</p>
<p>Beyond that, choosing among the valid options comes down to looking at the empirical variogram, thinking about the physical process you’re modeling, and comparing cross-validation skill. There is no one-size-fits-all approach.</p>
</section>
<section id="other-types-of-kriging" class="level2">
<h2 class="anchored" data-anchor-id="other-types-of-kriging">Other Types of Kriging</h2>
<p>We are just scratching the surface of what we can do with kriging. Think about what you might do in terms of interpolating in the presence of a trend? Or how to model anisotropy (see the <code>anis</code> argument to <code>vgm</code>). As with many topics in this class you could spend a whole quarter on kriging alone. Think of the pleasures invovled!</p>
</section>
<section id="cross-validation" class="level2">
<h2 class="anchored" data-anchor-id="cross-validation">Cross Validation</h2>
<p>I showed an example of using the built in cross validation function at the end of the last module. We can do the same with kriging. Instead of a straight call to <code>krige</code> we can call <code>krige.cv</code> for either k-fold or leave-one-out cross validation (LOOCV). It defaults to LOOCV so the predicted values are from the time they were left out the model.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>leadKrigeLOOCV_sf <span class="ot">&lt;-</span> <span class="fu">krige.cv</span>(<span class="at">formula =</span> logLead<span class="sc">~</span><span class="dv">1</span>, </span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>                           <span class="at">locations =</span> meuse_sf, </span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>                           <span class="at">model =</span> leadFit, <span class="at">verbose =</span> <span class="cn">FALSE</span>)</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>leadKrigeLOOCV_sf</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 164 features and 6 fields
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: 178605 ymin: 329714 xmax: 181390 ymax: 333611
Projected CRS: Amersfoort / RD New
First 10 features:
   var1.pred  var1.var observed    residual       zscore fold
1   5.402571 0.2277973 5.700444  0.29787270  0.624103170    1
2   5.473044 0.2199374 5.624018  0.15097361  0.321922586    2
3   5.233697 0.2180910 5.293305  0.05960821  0.127640125    3
4   5.077189 0.2520550 4.753590 -0.32359848 -0.644553277    4
5   4.794539 0.2134651 4.762174 -0.03236554 -0.070051822    5
6   4.584552 0.2571416 4.919981  0.33542860  0.661475719    6
7   4.970576 0.2088842 4.882802 -0.08777385 -0.192049137    7
8   5.253444 0.2072102 5.010635 -0.24280892 -0.533407471    8
9   4.886148 0.1786532 4.890349  0.00420153  0.009940359    9
10  4.589513 0.1984181 4.382027 -0.20748612 -0.465798826   10
                geometry
1  POINT (181072 333611)
2  POINT (181025 333558)
3  POINT (181165 333537)
4  POINT (181298 333484)
5  POINT (181307 333330)
6  POINT (181390 333260)
7  POINT (181165 333370)
8  POINT (181027 333363)
9  POINT (181060 333231)
10 POINT (181232 333168)</code></pre>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># CV R2 anbd RMSE</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>rsq <span class="ot">&lt;-</span> <span class="fu">cor</span>(leadKrigeLOOCV_sf<span class="sc">$</span>observed,leadKrigeLOOCV_sf<span class="sc">$</span>var1.pred)<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>rmse <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((leadKrigeLOOCV_sf<span class="sc">$</span>observed <span class="sc">-</span> leadKrigeLOOCV_sf<span class="sc">$</span>var1.pred)<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">rsq=</span>rsq, <span class="at">rmse =</span> rmse)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>      rsq      rmse 
0.6192935 0.4141229 </code></pre>
</div>
</div>
<p>The LOOCV R<span class="math inline">\(^2\)</span> is 0.619 and the RMSE is 0.414 which we get from the observed vs predicted values. But note all the fields we get from the <code>krige.cv</code> function. We get the prediction and prediction variance of the cross-validated data points and we also get the observed values. We also get the residuals (observed minus predicted), the z-score (the residual divided by kriging standard error), and the fold (in this case we have as many folds as rows in meuse because it is LOOCV).</p>
</section>
<section id="the-payoff" class="level2">
<h2 class="anchored" data-anchor-id="the-payoff">The Payoff</h2>
<p>Recall that IDW and TPS gave us a prediction surface with no uncertainty attached. Every grid cell got a number and that was that. Kriging gives us the same prediction surface, but also the variance surface we just looked at, and that second surface is where probability theory earns its keep. Imagine you’re deciding where to put additional soil sampling stations to reduce uncertainty in your lead concentration map. With IDW you have no principled way to answer that question, because IDW has no model of uncertainty to begin with. With kriging, you look at the variance surface and put your next sample where the variance is highest. Or imagine you need to flag grid cells where the predicted lead concentration exceeds a regulatory threshold: with a variance surface you can attach a probability to that exceedance rather than just a point estimate. The deterministic methods we covered earlier are fast and intuitive, but they borrow nothing from probability theory, so there is no statistically grounded way to quantify how much you should trust the predictions. Kriging trades some of that simplicity for something genuinely useful: a map of your own ignorance.</p>
</section>
<section id="your-work" class="level2">
<h2 class="anchored" data-anchor-id="your-work">Your Work</h2>
<p>Let’s turn again to the California precipitation data that you used for the IDW module. Like with IDW, you’ll make a continuous 10x10 km surface of precipitation from the 432 locations of long-term precipitation records. But this time you’ll krige the surface rather than use IDW.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># precip point data</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>prcpCA <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">"data/prcpCA.rds"</span>)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="co"># empty grid to interpolate into</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>gridCA <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">"data/gridCA.rds"</span>)</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>prcpCAsf <span class="ot">&lt;-</span> prcpCA <span class="sc">%&gt;%</span> <span class="fu">st_as_sf</span>(<span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"X"</span>, <span class="st">"Y"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_set_crs</span>(<span class="at">value =</span> <span class="dv">3310</span>)</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>prcpCAsf <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="fu">aes</span>(<span class="at">fill=</span>ANNUAL,<span class="at">size=</span>ANNUAL),<span class="at">color=</span><span class="st">"white"</span>,</span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>          <span class="at">shape=</span><span class="dv">21</span>,<span class="at">alpha=</span><span class="fl">0.8</span>) <span class="sc">+</span> </span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_continuous</span>(<span class="at">type =</span> <span class="st">"viridis"</span>,<span class="at">name=</span><span class="st">"mm"</span>) <span class="sc">+</span> </span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Total Annual Precipitation"</span>) <span class="sc">+</span></span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_size</span>(<span class="at">guide=</span><span class="st">"none"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="06aGeostatsKriging_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Use kriging to create a surface of total annual precipitation in California – do not use <code>automap</code> but fit the models using <code>variogram</code>, <code>vgm</code>, and <code>fit.variogram</code> as above. Compare at least two variogram models and assess the surface fit in a sensible way. Interpret and explain your surface and anything you notice in particular about it.</p>
</section>
<section id="postscript-automap" class="level2">
<h2 class="anchored" data-anchor-id="postscript-automap">Postscript: Automap</h2>
<p>You’ll find it anyways, so let’s get the cat out of the bag.</p>
<p>Like other angry old men, I like to describe a bucolic youth spent milking at 4AM, walking to school in the snow, programming F77 in vi, and <strong>doing all my GIS with Arc on the command line</strong>. Kids these days like to do their geostatistics in ArcGIS by clicking “next, next, next, finish” and plotting their map without <code>ARCPLOT</code>. One of the many reasons I like using <code>R</code> is that you get to do things like fit variograms by hand the same way the pioneers did when they had to cross the prairie. But you can, if you like, automatically fit a variogram using the <code>automap</code> library which has a lot of nice wrappers for the <code>gstat</code> functions like <code>fit.variogram</code>.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(automap)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>leadVar <span class="ot">&lt;-</span> <span class="fu">autofitVariogram</span>(<span class="at">formula =</span> logLead<span class="sc">~</span><span class="dv">1</span>,<span class="at">input_data =</span> meuse_sf)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(leadVar)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Experimental variogram:
     np       dist     gamma dir.hor dir.ver   id
1    17   59.33470 0.1270576       0       0 var1
2    39   86.73182 0.1905754       0       0 var1
3   126  130.83058 0.1487020       0       0 var1
4   171  176.60188 0.2540911       0       0 var1
5   198  226.70319 0.2378083       0       0 var1
6   810  338.36102 0.3395189       0       0 var1
7   957  502.89504 0.4191339       0       0 var1
8  1580  712.92647 0.5180130       0       0 var1
9  1500  961.00617 0.5738388       0       0 var1
10 1301 1212.86100 0.5675023       0       0 var1
11 1517 1504.85947 0.4954516       0       0 var1

Fitted variogram model:
  model      psill    range
1   Nug 0.09182989   0.0000
2   Sph 0.46323373 941.6887
Sums of squares betw. var. model and sample var.[1] 2.920612e-05</code></pre>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(leadVar)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="06aGeostatsKriging_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This automatically fits and plots a variogram like <code>fit.variogram</code> but instead of using user-supplied initial estimates for the model and the parameters, <code>autofitVariogram</code> makes these estimates based on the data and then calls <code>fit.variogram</code>. The automatic fitting above chose a spherical model like we did above but it tried all the models (exponential, Gaussian, Mattern, etc.) as part of the process.</p>
<p>The biggest difference is that <code>autofitVariogram</code> does the bins quite differently than <code>gstat</code>’s default behavior with <code>variogram</code>. Instead of equal widths, <code>autofitVariogram</code> creates bins of unequal widths. It passes these as the <code>boundaries</code> argument to <code>variogram</code>. You can look at the code for details (<code>getAnywhere(autofitVariogram)</code>) but the spirit is to try to get more leverage on the shortest distances to help estimate the wiggliest part of the variogram curve, especially the nugget. I think it makes sense.</p>
<p>Note that this plot (which is invoked for objects of class <code>autofitVariogram</code>) plots the number of point pairs at that distance as well as adds the model terms as a legend. You can look at the code for this plot via <code>getAnywhere(plot.autofitVariogram)</code> if you are curious.</p>
<p>And just to complete the whole automation thing, you can automatically apply cross validation as well. Since <code>autoKrige.cv</code> calls <code>krige.cv</code> to do a lot of the work, it defaults to LOOCV as above.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>leadAutoKrigeLOOCV <span class="ot">&lt;-</span> <span class="fu">autoKrige.cv</span>(<span class="at">formula =</span> logLead<span class="sc">~</span><span class="dv">1</span>, <span class="at">input_data =</span> meuse_sf,</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">verbose =</span> <span class="fu">c</span>(<span class="cn">FALSE</span>,<span class="cn">FALSE</span>))</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(leadAutoKrigeLOOCV)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>            [,1]      
mean_error  -0.002369 
me_mean     -0.0004967
MAE         0.2996    
MSE         0.1692    
MSNE        0.8531    
cor_obspred 0.7901    
cor_predres 0.04327   
RMSE        0.4113    
RMSE_sd     0.6117    
URMSE       0.4113    
iqr         0.4022    </code></pre>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># R2</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(leadAutoKrigeLOOCV<span class="sc">$</span>krige.cv_output<span class="sc">$</span>observed,leadAutoKrigeLOOCV<span class="sc">$</span>krige.cv_output<span class="sc">$</span>var1.pred)<span class="sc">^</span><span class="dv">2</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6242166</code></pre>
</div>
</div>
<p>Here we get a LOOCV R<span class="math inline">\(^2\)</span> of 0.6242 which is very (very) close to what we got with the cross validation we did manually above.</p>
<p><strong>Use the tools in <code>automap</code> with caution however. Beware the black box.</strong></p>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-bivand2008geostatistics" class="csl-entry" role="listitem">
Bivand, Roger. 2008. <span>“Interpolation and Geostatistics.”</span> In <em>Applied Spatial Data Analysis with <span>R</span></em>, edited by Roger Bivand, Edzer J. Pebesma, and Virgilio Gómez-Rubio. Use <span>R</span>! Springer.
</div>
<div id="ref-fortin2016spatial" class="csl-entry" role="listitem">
Fortin, Marie-Josèe, Mark R. T. Dale, and Jay M. Ver Hoef. 2016. <span>“Spatial Analysis in Ecology.”</span> In <em>Wiley <span>StatsRef</span>: Statistics Reference Online</em>, edited by N. Balakrishnan, T. Colton, B. Everitt, W. Piegorsch, F. Ruggeri, and J. L. Teugels. John Wiley &amp; Sons. <a href="https://doi.org/10.1002/9781118445112.stat07766">https://doi.org/10.1002/9781118445112.stat07766</a>.
</div>
<div id="ref-R-tidyterra" class="csl-entry" role="listitem">
Hernangómez, Diego. 2023. <span>“Using the <span class="nocase">tidyverse</span> with <span class="nocase">terra</span> Objects: The <span class="nocase">tidyterra</span> Package.”</span> <em>Journal of Open Source Software</em> 8 (91): 5751. <a href="https://doi.org/10.21105/joss.05751">https://doi.org/10.21105/joss.05751</a>.
</div>
<div id="ref-R-automap" class="csl-entry" role="listitem">
Hiemstra, P. H., E. J. Pebesma, C. J. W. Twenh"ofel, and G. B. M. Heuvelink. 2008. <span>“Real-Time Automatic Interpolation of Ambient Gamma Dose Rates from the Dutch Radioactivity Monitoring Network.”</span> <em>Computers &amp; Geosciences</em>.
</div>
<div id="ref-R-terra" class="csl-entry" role="listitem">
Hijmans, Robert J. 2026. <em>Terra: Spatial Data Analysis</em>. <a href="https://rspatial.org/">https://rspatial.org/</a>.
</div>
<div id="ref-R-sf" class="csl-entry" role="listitem">
Pebesma, Edzer. 2026. <em>Sf: Simple Features for r</em>. <a href="https://r-spatial.github.io/sf/">https://r-spatial.github.io/sf/</a>.
</div>
<div id="ref-R-gstat" class="csl-entry" role="listitem">
Pebesma, Edzer, and Benedikt Graeler. 2026. <em>Gstat: Spatial and Spatio-Temporal Geostatistical Modelling, Prediction and Simulation</em>. <a href="https://github.com/r-spatial/gstat/">https://github.com/r-spatial/gstat/</a>.
</div>
<div id="ref-R-tidyverse" class="csl-entry" role="listitem">
Wickham, Hadley. 2023. <em>Tidyverse: Easily Install and Load the Tidyverse</em>. <a href="https://tidyverse.tidyverse.org">https://tidyverse.tidyverse.org</a>.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./05bGeostat2TPS.html" class="pagination-link" aria-label="Deterministic Interpolation: Thin-Plate Splines">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Deterministic Interpolation: Thin-Plate Splines</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./06xAsideGeostatsKrigingVariance.html" class="pagination-link" aria-label="Aside: Kriging Variance By Hand">
        <span class="nav-page-text">Aside: Kriging Variance By Hand</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/AndyBunn/spatialNotes/edit/main/06aGeostatsKriging.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/AndyBunn/spatialNotes/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer></body></html>